/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class Category_Name extends javax.swing.JFrame {

    /**
     * Creates new form Category_Name
     */
    public Category_Name() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(26, 2, 2));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(26, 2, 2));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(201, 201, 201));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(26, 2, 2));
        jButton1.setText("حفظ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 80, 66, 30);

        jButton2.setBackground(new java.awt.Color(201, 201, 201));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(26, 2, 2));
        jButton2.setText("الغاء");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 80, 66, 30);

        cat.setBackground(new java.awt.Color(255, 255, 255));
        cat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cat.setForeground(new java.awt.Color(26, 2, 2));
        cat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(cat);
        cat.setBounds(20, 40, 165, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(201, 201, 201));
        jLabel2.setText("الموديل :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 45, 80, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 306, 129);

        setSize(new java.awt.Dimension(305, 128));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ("".equals(cat.getText())) {
            JOptionPane.showMessageDialog(this, "املئ البيانات", "خطأ", JOptionPane.WARNING_MESSAGE);
        } else {
            String save = "INSERT INTO CATEGORY VALUES ('" + cat.getText() + "')";
            int co = JOptionPane.showConfirmDialog(this, "هل تريد الحفظ", "تأكيد", JOptionPane.WARNING_MESSAGE);
            if (co == JOptionPane.YES_OPTION) {
                boolean ifS = DB.MethodsDB.runNunQuery(save);
                if (ifS) {
                    JOptionPane.showMessageDialog(this, "تم حفظ البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                    DB.MethodsDB.fillCompo("category", "model", StorageFrm.jModel);
                    StorageFrm.jModel.setSelectedItem(cat.getText());
                    cat.setText("");
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "لم يتم الحفظ", "خطأ", JOptionPane.ERROR_MESSAGE);
                }

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Category_Name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Category_Name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Category_Name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Category_Name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Category_Name().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
