/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controls.Tools;
import Entity.DashboardChart;
import java.awt.Color;
import java.awt.event.MouseEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class HomeFrm extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrm
     */
    public HomeFrm() {
        initComponents();
        DashboardChart dashb = new DashboardChart();

        BarChart.removeAll();
        dashb.getBarChart(BarChart);
        BarChart.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        H = new javax.swing.JPanel();
        Bar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        closebtn = new javax.swing.JLabel();
        maxi = new javax.swing.JPanel();
        maxibtn = new javax.swing.JLabel();
        mini = new javax.swing.JPanel();
        minibtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        inir = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        l = new javax.swing.JLabel();
        usersbtn = new javax.swing.JButton();
        Logoutbtn = new javax.swing.JButton();
        down = new javax.swing.JPanel();
        Salebtn = new javax.swing.JButton();
        AddNewbtn = new javax.swing.JButton();
        Stockbtn = new javax.swing.JButton();
        Accountsbtn = new javax.swing.JButton();
        Reportsbtn = new javax.swing.JButton();
        Notesbtn = new javax.swing.JButton();
        Dashboard = new javax.swing.JPanel();
        BarChart = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        H.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(26, 2, 2)));
        H.setLayout(new java.awt.BorderLayout());

        Bar.setPreferredSize(new java.awt.Dimension(100, 30));
        Bar.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(26, 2, 2));
        jPanel2.setLayout(new java.awt.BorderLayout());

        close.setBackground(new java.awt.Color(36, 2, 2));
        close.setPreferredSize(new java.awt.Dimension(30, 30));
        close.setLayout(new java.awt.BorderLayout());

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_close_window_26px.png"))); // NOI18N
        closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closebtnMouseExited(evt);
            }
        });
        close.add(closebtn, java.awt.BorderLayout.CENTER);

        jPanel2.add(close, java.awt.BorderLayout.LINE_END);

        maxi.setBackground(new java.awt.Color(26, 2, 2));
        maxi.setPreferredSize(new java.awt.Dimension(30, 30));
        maxi.setLayout(new java.awt.BorderLayout());

        maxibtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_maximize_window_26px_1.png"))); // NOI18N
        maxibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maxibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxibtnMouseExited(evt);
            }
        });
        maxi.add(maxibtn, java.awt.BorderLayout.CENTER);

        jPanel2.add(maxi, java.awt.BorderLayout.CENTER);

        mini.setBackground(new java.awt.Color(26, 2, 2));
        mini.setPreferredSize(new java.awt.Dimension(30, 30));
        mini.setLayout(new java.awt.BorderLayout());

        minibtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_26px.png"))); // NOI18N
        minibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minibtnMouseExited(evt);
            }
        });
        mini.add(minibtn, java.awt.BorderLayout.CENTER);

        jPanel2.add(mini, java.awt.BorderLayout.LINE_START);

        Bar.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(26, 2, 2));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(201, 201, 201));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("الصفحة الرئيسية");
        jPanel3.add(jLabel2, java.awt.BorderLayout.CENTER);

        Bar.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(26, 2, 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 100));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minlo.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        Bar.add(jPanel1, java.awt.BorderLayout.LINE_START);

        H.add(Bar, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setPreferredSize(new java.awt.Dimension(290, 100));
        Menu.setLayout(new java.awt.BorderLayout());

        inir.setBackground(new java.awt.Color(255, 255, 255));
        inir.setLayout(new java.awt.BorderLayout());

        top.setBackground(new java.awt.Color(201, 201, 201));
        top.setPreferredSize(new java.awt.Dimension(300, 150));
        top.setLayout(null);

        l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/l.png"))); // NOI18N
        top.add(l);
        l.setBounds(100, 20, 70, 80);

        name.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        name.setForeground(new java.awt.Color(26, 2, 2));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top.add(name);
        name.setBounds(50, 110, 190, 30);

        usersbtn.setBackground(new java.awt.Color(26, 2, 2));
        usersbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        usersbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_user_group_man_man_25px.png"))); // NOI18N
        usersbtn.setToolTipText("اضافة مستخدم");
        usersbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersbtnActionPerformed(evt);
            }
        });
        top.add(usersbtn);
        usersbtn.setBounds(0, 0, 40, 40);

        Logoutbtn.setBackground(new java.awt.Color(26, 2, 2));
        Logoutbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_logout_rounded_left_20px.png"))); // NOI18N
        Logoutbtn.setToolTipText("تسجيل خروج");
        Logoutbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });
        top.add(Logoutbtn);
        Logoutbtn.setBounds(0, 40, 40, 40);

        inir.add(top, java.awt.BorderLayout.PAGE_START);

        down.setBackground(new java.awt.Color(201, 201, 201));
        down.setPreferredSize(new java.awt.Dimension(200, 100));
        down.setLayout(new java.awt.GridBagLayout());

        Salebtn.setBackground(new java.awt.Color(26, 2, 2));
        Salebtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Salebtn.setForeground(new java.awt.Color(201, 201, 201));
        Salebtn.setText("بيع");
        Salebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalebtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 40, 0, 40);
        down.add(Salebtn, gridBagConstraints);

        AddNewbtn.setBackground(new java.awt.Color(26, 2, 2));
        AddNewbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        AddNewbtn.setForeground(new java.awt.Color(201, 201, 201));
        AddNewbtn.setText("إضافة صنف جديد");
        AddNewbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddNewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 40, 0, 40);
        down.add(AddNewbtn, gridBagConstraints);

        Stockbtn.setBackground(new java.awt.Color(26, 2, 2));
        Stockbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Stockbtn.setForeground(new java.awt.Color(201, 201, 201));
        Stockbtn.setText("المخزن");
        Stockbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 137;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 40, 0, 40);
        down.add(Stockbtn, gridBagConstraints);

        Accountsbtn.setBackground(new java.awt.Color(26, 2, 2));
        Accountsbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Accountsbtn.setForeground(new java.awt.Color(201, 201, 201));
        Accountsbtn.setText("الحسابات");
        Accountsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Accountsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountsbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 40, 0, 40);
        down.add(Accountsbtn, gridBagConstraints);

        Reportsbtn.setBackground(new java.awt.Color(26, 2, 2));
        Reportsbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Reportsbtn.setForeground(new java.awt.Color(201, 201, 201));
        Reportsbtn.setText("تقارير");
        Reportsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reportsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 40, 0, 40);
        down.add(Reportsbtn, gridBagConstraints);

        Notesbtn.setBackground(new java.awt.Color(26, 2, 2));
        Notesbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Notesbtn.setForeground(new java.awt.Color(201, 201, 201));
        Notesbtn.setText("ملاحظات ");
        Notesbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Notesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotesbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 40, 29, 40);
        down.add(Notesbtn, gridBagConstraints);

        inir.add(down, java.awt.BorderLayout.CENTER);

        Menu.add(inir, java.awt.BorderLayout.CENTER);

        H.add(Menu, java.awt.BorderLayout.LINE_START);

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard.setLayout(new java.awt.BorderLayout());

        BarChart.setBackground(new java.awt.Color(255, 255, 255));
        BarChart.setLayout(new java.awt.BorderLayout());
        Dashboard.add(BarChart, java.awt.BorderLayout.CENTER);

        H.add(Dashboard, java.awt.BorderLayout.CENTER);

        getContentPane().add(H, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1095, 633));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        int ifY = JOptionPane.showConfirmDialog(null, "هل تريد إغلاق البرنامج ؟");
        if (ifY == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_closebtnMouseClicked

    private void minibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.setState(WIDTH);
        }
    }//GEN-LAST:event_minibtnMouseClicked

    private void closebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseEntered
        close.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_closebtnMouseEntered

    private void closebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseExited
        close.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_closebtnMouseExited

    private void maxibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseEntered
        maxi.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_maxibtnMouseEntered

    private void maxibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseExited
        maxi.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_maxibtnMouseExited

    private void minibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseEntered
        mini.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_minibtnMouseEntered

    private void minibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseExited
        mini.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_minibtnMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        name.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        this.dispose();
        Tools.openFram(new LoginFrm());
    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void maxibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseClicked
        if (this.getExtendedState() != HomeFrm.MAXIMIZED_BOTH) {
            this.setExtendedState(HomeFrm.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(HomeFrm.NORMAL);
        }
    }//GEN-LAST:event_maxibtnMouseClicked

    private void SalebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalebtnActionPerformed
        this.dispose();
        Tools.openFram(new SaleFrm());
    }//GEN-LAST:event_SalebtnActionPerformed

    private void AddNewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewbtnActionPerformed
        this.dispose();
        Tools.openFram(new StorageFrm());
    }//GEN-LAST:event_AddNewbtnActionPerformed

    private void StockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockbtnActionPerformed
        this.dispose();
        Tools.openFram(new StoreFrm());
    }//GEN-LAST:event_StockbtnActionPerformed

    private void ReportsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsbtnActionPerformed
        this.dispose();
        Tools.openFram(new ReportsFrm());
    }//GEN-LAST:event_ReportsbtnActionPerformed

    private void AccountsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountsbtnActionPerformed
        this.dispose();
        Tools.openFram(new AccountsFrm());
    }//GEN-LAST:event_AccountsbtnActionPerformed

    private void NotesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotesbtnActionPerformed
        this.dispose();
        Tools.openFram(new NotesFrm());
    }//GEN-LAST:event_NotesbtnActionPerformed

    private void usersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersbtnActionPerformed
        this.dispose();
        Tools.openFram(new UsersFrm());
    }//GEN-LAST:event_usersbtnActionPerformed
    String path = null;
    String filename;
    Process p = null;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accountsbtn;
    private javax.swing.JButton AddNewbtn;
    private javax.swing.JPanel Bar;
    private javax.swing.JPanel BarChart;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel H;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Notesbtn;
    private javax.swing.JButton Reportsbtn;
    private javax.swing.JButton Salebtn;
    private javax.swing.JButton Stockbtn;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closebtn;
    private javax.swing.JPanel down;
    private javax.swing.JPanel inir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel l;
    private javax.swing.JPanel maxi;
    private javax.swing.JLabel maxibtn;
    private javax.swing.JPanel mini;
    private javax.swing.JLabel minibtn;
    public static final javax.swing.JLabel name = new javax.swing.JLabel();
    private javax.swing.JPanel top;
    private javax.swing.JButton usersbtn;
    // End of variables declaration//GEN-END:variables
}
