/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controls.Tools;
import DB.MethodsDB;
import Entity.Notes;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class NotesFrm extends javax.swing.JFrame {

    /**
     * Creates new form NotesFrm
     */
    public NotesFrm() {
        initComponents();
        all.setVisible(false);
        all.setEnabled(false);
        date.setVisible(false);
        date.setEnabled(false);
        updatebtn.setEnabled(false);
        deletebtn.setEnabled(false);
        paymentbtn.setEnabled(false);
        idtxt.setVisible(false);
        idtxt.setEnabled(false);
        Tools.tableUI(jTable1, 6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bar = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        closebtn = new javax.swing.JLabel();
        maxi = new javax.swing.JPanel();
        maxibtn = new javax.swing.JLabel();
        mini = new javax.swing.JPanel();
        minibtn = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        buttons = new javax.swing.JPanel();
        btnhome = new javax.swing.JButton();
        notpaidbtn = new javax.swing.JButton();
        oldbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        fildes = new javax.swing.JPanel();
        nameLab = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        phoneLab = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        dateLab = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        costLab = new javax.swing.JLabel();
        costtxt = new javax.swing.JTextField();
        notesLab = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notestxt = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        searchLab = new javax.swing.JLabel();
        btnall = new javax.swing.JRadioButton();
        btndate = new javax.swing.JRadioButton();
        date = new javax.swing.JPanel();
        searchallbtn1 = new javax.swing.JButton();
        jLabfrom = new javax.swing.JLabel();
        datefrom = new com.toedter.calendar.JDateChooser();
        jLabto = new javax.swing.JLabel();
        dateto = new com.toedter.calendar.JDateChooser();
        all = new javax.swing.JPanel();
        searchtxt = new javax.swing.JTextField();
        searchallbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        paymentbtn = new javax.swing.JButton();
        idtxt = new javax.swing.JTextField();
        table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(26, 2, 2)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        bar.setPreferredSize(new java.awt.Dimension(1280, 30));
        bar.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(26, 2, 2));
        jPanel10.setLayout(new java.awt.BorderLayout());

        close.setBackground(new java.awt.Color(36, 2, 2));
        close.setPreferredSize(new java.awt.Dimension(30, 30));
        close.setLayout(new java.awt.BorderLayout());

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_close_window_26px.png"))); // NOI18N
        closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closebtnMouseExited(evt);
            }
        });
        close.add(closebtn, java.awt.BorderLayout.CENTER);

        jPanel10.add(close, java.awt.BorderLayout.LINE_END);

        maxi.setBackground(new java.awt.Color(26, 2, 2));
        maxi.setPreferredSize(new java.awt.Dimension(30, 30));
        maxi.setLayout(new java.awt.BorderLayout());

        maxibtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_maximize_window_26px_1.png"))); // NOI18N
        maxibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maxibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxibtnMouseExited(evt);
            }
        });
        maxi.add(maxibtn, java.awt.BorderLayout.CENTER);

        jPanel10.add(maxi, java.awt.BorderLayout.CENTER);

        mini.setBackground(new java.awt.Color(26, 2, 2));
        mini.setPreferredSize(new java.awt.Dimension(30, 30));
        mini.setLayout(new java.awt.BorderLayout());

        minibtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_26px.png"))); // NOI18N
        minibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minibtnMouseExited(evt);
            }
        });
        mini.add(minibtn, java.awt.BorderLayout.CENTER);

        jPanel10.add(mini, java.awt.BorderLayout.LINE_START);

        bar.add(jPanel10, java.awt.BorderLayout.LINE_END);

        jPanel13.setBackground(new java.awt.Color(26, 2, 2));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(201, 201, 201));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("الملاحظات");
        jPanel13.add(jLabel2, java.awt.BorderLayout.CENTER);

        bar.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel14.setBackground(new java.awt.Color(26, 2, 2));
        jPanel14.setPreferredSize(new java.awt.Dimension(50, 100));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minlo.png"))); // NOI18N
        jPanel14.add(jLabel5, java.awt.BorderLayout.CENTER);

        bar.add(jPanel14, java.awt.BorderLayout.LINE_START);

        jPanel1.add(bar, java.awt.BorderLayout.PAGE_START);

        body.setLayout(new java.awt.BorderLayout());

        buttons.setBackground(new java.awt.Color(201, 201, 201));
        buttons.setPreferredSize(new java.awt.Dimension(250, 300));
        buttons.setLayout(new java.awt.GridBagLayout());

        btnhome.setBackground(new java.awt.Color(26, 2, 2));
        btnhome.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btnhome.setForeground(new java.awt.Color(201, 201, 201));
        btnhome.setText("الصفحة الرئيسية");
        btnhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 0, 20);
        buttons.add(btnhome, gridBagConstraints);

        notpaidbtn.setBackground(new java.awt.Color(26, 2, 2));
        notpaidbtn.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        notpaidbtn.setForeground(new java.awt.Color(201, 201, 201));
        notpaidbtn.setText("لم يتم سداده");
        notpaidbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notpaidbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notpaidbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 116;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 10, 0, 20);
        buttons.add(notpaidbtn, gridBagConstraints);

        oldbtn.setBackground(new java.awt.Color(26, 2, 2));
        oldbtn.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        oldbtn.setForeground(new java.awt.Color(201, 201, 201));
        oldbtn.setText("الارشيف");
        oldbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oldbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 142;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 20);
        buttons.add(oldbtn, gridBagConstraints);

        savebtn.setBackground(new java.awt.Color(26, 2, 2));
        savebtn.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        savebtn.setForeground(new java.awt.Color(201, 201, 201));
        savebtn.setText("حفظ");
        savebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 10, 20);
        buttons.add(savebtn, gridBagConstraints);

        body.add(buttons, java.awt.BorderLayout.LINE_START);

        fildes.setBackground(new java.awt.Color(255, 255, 255));
        fildes.setLayout(new java.awt.GridBagLayout());

        nameLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        nameLab.setForeground(new java.awt.Color(26, 2, 2));
        nameLab.setText("الأسم :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 10, 0, 0);
        fildes.add(nameLab, gridBagConstraints);

        nametxt.setBackground(new java.awt.Color(201, 201, 201));
        nametxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nametxt.setForeground(new java.awt.Color(26, 2, 2));
        nametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, phonetxt, org.jdesktop.beansbinding.ObjectProperty.create(), nametxt, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 166;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 100, 0, 0);
        fildes.add(nametxt, gridBagConstraints);

        phoneLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        phoneLab.setForeground(new java.awt.Color(26, 2, 2));
        phoneLab.setText("الموبايل :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 10, 0, 0);
        fildes.add(phoneLab, gridBagConstraints);

        phonetxt.setBackground(new java.awt.Color(201, 201, 201));
        phonetxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        phonetxt.setForeground(new java.awt.Color(26, 2, 2));
        phonetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jDateChooser1, org.jdesktop.beansbinding.ObjectProperty.create(), phonetxt, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 166;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 100, 0, 0);
        fildes.add(phonetxt, gridBagConstraints);

        dateLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        dateLab.setForeground(new java.awt.Color(26, 2, 2));
        dateLab.setText("التاريخ :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 10, 0, 0);
        fildes.add(dateLab, gridBagConstraints);

        jDateChooser1.setBackground(new java.awt.Color(201, 201, 201));
        jDateChooser1.setForeground(new java.awt.Color(26, 2, 2));
        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, costtxt, org.jdesktop.beansbinding.ObjectProperty.create(), jDateChooser1, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 50, 0, 0);
        fildes.add(jDateChooser1, gridBagConstraints);

        costLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        costLab.setForeground(new java.awt.Color(26, 2, 2));
        costLab.setText("المبلغ :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 10, 0, 0);
        fildes.add(costLab, gridBagConstraints);

        costtxt.setBackground(new java.awt.Color(201, 201, 201));
        costtxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        costtxt.setForeground(new java.awt.Color(26, 2, 2));
        costtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, notestxt, org.jdesktop.beansbinding.ObjectProperty.create(), costtxt, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 166;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 50, 0, 0);
        fildes.add(costtxt, gridBagConstraints);

        notesLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        notesLab.setForeground(new java.awt.Color(26, 2, 2));
        notesLab.setText("ملاحظات :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 10, 0, 0);
        fildes.add(notesLab, gridBagConstraints);

        jScrollPane2.setBackground(new java.awt.Color(201, 201, 201));
        jScrollPane2.setForeground(new java.awt.Color(26, 2, 2));

        notestxt.setBackground(new java.awt.Color(201, 201, 201));
        notestxt.setColumns(20);
        notestxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        notestxt.setForeground(new java.awt.Color(26, 2, 2));
        notestxt.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, savebtn, org.jdesktop.beansbinding.ObjectProperty.create(), notestxt, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(notestxt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 50, 0, 0);
        fildes.add(jScrollPane2, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        searchLab.setBackground(new java.awt.Color(255, 255, 255));
        searchLab.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        searchLab.setForeground(new java.awt.Color(26, 2, 2));
        searchLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchLab.setText("بحث بــــ :");
        jPanel7.add(searchLab);
        searchLab.setBounds(670, 20, 43, 17);

        btnall.setBackground(new java.awt.Color(255, 255, 255));
        btnall.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnall.setForeground(new java.awt.Color(26, 2, 2));
        btnall.setText("الكل");
        btnall.setOpaque(false);
        btnall.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnallItemStateChanged(evt);
            }
        });
        jPanel7.add(btnall);
        btnall.setBounds(610, 15, 51, 28);

        btndate.setBackground(new java.awt.Color(255, 255, 255));
        btndate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btndate.setForeground(new java.awt.Color(26, 2, 2));
        btndate.setText("التاريخ");
        btndate.setOpaque(false);
        btndate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndateItemStateChanged(evt);
            }
        });
        jPanel7.add(btndate);
        btndate.setBounds(532, 15, 80, 28);

        date.setBackground(new java.awt.Color(255, 255, 255));
        date.setLayout(null);

        searchallbtn1.setBackground(new java.awt.Color(26, 2, 2));
        searchallbtn1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        searchallbtn1.setForeground(new java.awt.Color(201, 201, 201));
        searchallbtn1.setText("بحث");
        searchallbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchallbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchallbtn1ActionPerformed(evt);
            }
        });
        date.add(searchallbtn1);
        searchallbtn1.setBounds(20, 15, 70, 30);

        jLabfrom.setForeground(new java.awt.Color(26, 2, 2));
        jLabfrom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabfrom.setText("من");
        date.add(jLabfrom);
        jLabfrom.setBounds(480, 20, 20, 20);

        datefrom.setBackground(new java.awt.Color(201, 201, 201));
        datefrom.setForeground(new java.awt.Color(26, 2, 2));
        datefrom.setDateFormatString("yyyy-MM-dd");
        date.add(datefrom);
        datefrom.setBounds(310, 15, 160, 29);

        jLabto.setForeground(new java.awt.Color(26, 2, 2));
        jLabto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabto.setText("إلى");
        date.add(jLabto);
        jLabto.setBounds(283, 20, 20, 20);

        dateto.setBackground(new java.awt.Color(201, 201, 201));
        dateto.setForeground(new java.awt.Color(26, 2, 2));
        dateto.setDateFormatString("yyyy-MM-dd");
        date.add(dateto);
        dateto.setBounds(120, 15, 160, 29);

        jPanel7.add(date);
        date.setBounds(0, 0, 510, 50);

        all.setBackground(new java.awt.Color(255, 255, 255));
        all.setLayout(null);

        searchtxt.setBackground(new java.awt.Color(201, 201, 201));
        searchtxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        searchtxt.setForeground(new java.awt.Color(26, 2, 2));
        searchtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        all.add(searchtxt);
        searchtxt.setBounds(109, 15, 390, 30);

        searchallbtn.setBackground(new java.awt.Color(26, 2, 2));
        searchallbtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        searchallbtn.setForeground(new java.awt.Color(201, 201, 201));
        searchallbtn.setText("بحث");
        searchallbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchallbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchallbtnActionPerformed(evt);
            }
        });
        all.add(searchallbtn);
        searchallbtn.setBounds(20, 15, 70, 30);

        jPanel7.add(all);
        all.setBounds(0, 0, 510, 50);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 719;
        gridBagConstraints.ipady = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 30, 0, 7);
        fildes.add(jPanel7, gridBagConstraints);

        updatebtn.setBackground(new java.awt.Color(26, 2, 2));
        updatebtn.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(201, 201, 201));
        updatebtn.setText("تعديل");
        updatebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 10, 8, 0);
        fildes.add(updatebtn, gridBagConstraints);

        deletebtn.setBackground(new java.awt.Color(26, 2, 2));
        deletebtn.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(201, 201, 201));
        deletebtn.setText("حذف");
        deletebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 10, 8, 0);
        fildes.add(deletebtn, gridBagConstraints);

        paymentbtn.setBackground(new java.awt.Color(26, 2, 2));
        paymentbtn.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        paymentbtn.setForeground(new java.awt.Color(201, 201, 201));
        paymentbtn.setText("سدد");
        paymentbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 10, 8, 0);
        fildes.add(paymentbtn, gridBagConstraints);

        idtxt.setEditable(false);
        idtxt.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 80, 0, 0);
        fildes.add(idtxt, gridBagConstraints);

        body.add(fildes, java.awt.BorderLayout.CENTER);

        jPanel1.add(body, java.awt.BorderLayout.CENTER);

        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setPreferredSize(new java.awt.Dimension(1280, 350));
        table.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ملاحظات", "حالة السداد", "الموبايل", "المبلغ", "الاسم", "التاريخ", "التسلسل"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(184, 26, 61));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        table.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(table, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1281, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    Notes n = new Notes();

    private void setValues() {
        n.setId(Integer.parseInt(idtxt.getText()));
        Date d = new Date();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        n.setDate(f.format(jDateChooser1.getDate()));
        n.setName(nametxt.getText());
        n.setCost(Double.parseDouble(costtxt.getText()));
        n.setPhone(phonetxt.getText());
        n.setNotes(notestxt.getText());
        n.setPayment("لم يسدد");
    }
    String payment = "لم يسدد";
    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        int ifY = JOptionPane.showConfirmDialog(null, "هل تريد إغلاق البرنامج ؟");
        if (ifY == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_closebtnMouseClicked

    private void closebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseEntered
        close.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_closebtnMouseEntered

    private void closebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseExited
        close.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_closebtnMouseExited

    private void maxibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseClicked
        if (this.getExtendedState() != HomeFrm.MAXIMIZED_BOTH) {
            this.setExtendedState(HomeFrm.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(HomeFrm.NORMAL);
        }
    }//GEN-LAST:event_maxibtnMouseClicked

    private void maxibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseEntered
        maxi.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_maxibtnMouseEntered

    private void maxibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseExited
        maxi.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_maxibtnMouseExited

    private void minibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.setState(WIDTH);
        }
    }//GEN-LAST:event_minibtnMouseClicked

    private void minibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseEntered
        mini.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_minibtnMouseEntered

    private void minibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseExited
        mini.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_minibtnMouseExited

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        this.dispose();
        Tools.openFram(new HomeFrm());
    }//GEN-LAST:event_btnhomeActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        if (idtxt.getText().equals("") || nametxt.getText().equals("") || costtxt.getText().equals("")) {
            Tools.msgbox("ادخل البيانات اولا");
        } else {
            setValues();
            n.add();
            Tools.clearText(this);
            notestxt.setText("");
            jDateChooser1.setCalendar(null);
            idtxt.setText(MethodsDB.getAutoNumber("notes", "id"));
            n.getAllRowsNotPayment(jTable1);
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void notpaidbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notpaidbtnActionPerformed
        payment = "لم يسدد";
        n.getAllRowsNotPayment(jTable1);
        Tools.clearText(this);
        jDateChooser1.setCalendar(null);
        idtxt.setText(MethodsDB.getAutoNumber("notes", "id"));
        updatebtn.setEnabled(false);
        deletebtn.setEnabled(false);
        paymentbtn.setEnabled(false);
        savebtn.setEnabled(true);
    }//GEN-LAST:event_notpaidbtnActionPerformed

    private void btnallItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnallItemStateChanged
        all.setVisible(true);
        all.setEnabled(true);
        date.setVisible(false);
        date.setEnabled(false);
    }//GEN-LAST:event_btnallItemStateChanged

    private void btndateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndateItemStateChanged
        all.setVisible(false);
        all.setEnabled(false);
        date.setVisible(true);
        date.setEnabled(true);
    }//GEN-LAST:event_btndateItemStateChanged

    private void oldbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldbtnActionPerformed
        payment = "سدد";
        n.getAllRowsOld(jTable1);
        Tools.clearText(this);
        jDateChooser1.setCalendar(null);
        idtxt.setText(MethodsDB.getAutoNumber("notes", "id"));
        updatebtn.setEnabled(false);
        deletebtn.setEnabled(false);
        paymentbtn.setEnabled(false);
        savebtn.setEnabled(true);
    }//GEN-LAST:event_oldbtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        buttonGroup1.add(btnall);
        buttonGroup1.add(btndate);
        idtxt.setText(MethodsDB.getAutoNumber("notes", "id"));
        n.getAllRowsNotPayment(jTable1);
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            int row = jTable1.getSelectedRow();
            String notes = jTable1.getValueAt(row, 0).toString();
            String pay = jTable1.getValueAt(row, 1).toString();
            String phone = jTable1.getValueAt(row, 2).toString();
            String cost = jTable1.getValueAt(row, 3).toString();
            String name = jTable1.getValueAt(row, 4).toString();
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            Date date = f.parse(jTable1.getValueAt(row, 5).toString());
            String id = jTable1.getValueAt(row, 6).toString();

            notestxt.setText(notes);
            phonetxt.setText(phone);
            costtxt.setText(cost);
            nametxt.setText(name);
            jDateChooser1.setDate(date);
            idtxt.setText(id);

            updatebtn.setEnabled(true);
            deletebtn.setEnabled(true);
            savebtn.setEnabled(false);
            if (pay.equals("لم يسدد")) {
                paymentbtn.setEnabled(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        if (idtxt.getText().equals("") || nametxt.getText().equals("") || costtxt.getText().equals("")) {
            Tools.msgbox("ادخل البيانات اولا");
        } else {
            setValues();
            n.update();
            Tools.clearText(this);
            notestxt.setText("");
            jDateChooser1.setCalendar(null);
            idtxt.setText(MethodsDB.getAutoNumber("notes", "id"));
            updatebtn.setEnabled(false);
            deletebtn.setEnabled(false);
            paymentbtn.setEnabled(false);
            savebtn.setEnabled(true);
            n.getAllRowsNotPayment(jTable1);
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        boolean ifyes = Tools.confirmMsg("هل تريد الحذف ");
        if (ifyes == true) {
            n.delete(idtxt.getText());
            Tools.clearText(this);
            jDateChooser1.setCalendar(null);
            idtxt.setText(MethodsDB.getAutoNumber("notes", "id"));
            updatebtn.setEnabled(false);
            deletebtn.setEnabled(false);
            paymentbtn.setEnabled(false);
            savebtn.setEnabled(true);
            n.getAllRowsNotPayment(jTable1);
        } else {
            System.out.println("no deleted");
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void paymentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentbtnActionPerformed
        n.Payment(idtxt.getText());
        Tools.clearText(this);
        jDateChooser1.setCalendar(null);
        idtxt.setText(MethodsDB.getAutoNumber("notes", "id"));
        updatebtn.setEnabled(false);
        deletebtn.setEnabled(false);
        paymentbtn.setEnabled(false);
        savebtn.setEnabled(true);
        n.getAllRowsNotPayment(jTable1);
    }//GEN-LAST:event_paymentbtnActionPerformed

    private void searchallbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchallbtn1ActionPerformed
        if (datefrom.getCalendar() != null) {
            if (dateto.getCalendar() == null) {
                SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
                String df = f.format(datefrom.getDate());
                n.getBillByOneDate(df, payment, jTable1);
            } else {
                SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
                String dfr = f.format(datefrom.getDate());
                String dt = f.format(dateto.getDate());
                n.getBillByManyDate(dfr, dt, payment, jTable1);
            }
        } else {
            Tools.msgbox("ادخل التاريخ اولا");
        }
    }//GEN-LAST:event_searchallbtn1ActionPerformed

    private void searchallbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchallbtnActionPerformed
        if (searchtxt.getText().equals("")) {
            Tools.msgbox("ادخل كلمات البحث اولا");
        } else {
            n.getBySearch(searchtxt.getText(), payment, jTable1);
        }
    }//GEN-LAST:event_searchallbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotesFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel all;
    private javax.swing.JPanel bar;
    private javax.swing.JPanel body;
    private javax.swing.JRadioButton btnall;
    private javax.swing.JRadioButton btndate;
    private javax.swing.JButton btnhome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel buttons;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel costLab;
    private javax.swing.JTextField costtxt;
    private javax.swing.JPanel date;
    private javax.swing.JLabel dateLab;
    private com.toedter.calendar.JDateChooser datefrom;
    private com.toedter.calendar.JDateChooser dateto;
    private javax.swing.JButton deletebtn;
    private javax.swing.JPanel fildes;
    private javax.swing.JTextField idtxt;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabfrom;
    private javax.swing.JLabel jLabto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel maxi;
    private javax.swing.JLabel maxibtn;
    private javax.swing.JPanel mini;
    private javax.swing.JLabel minibtn;
    private javax.swing.JLabel nameLab;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel notesLab;
    private javax.swing.JTextArea notestxt;
    private javax.swing.JButton notpaidbtn;
    private javax.swing.JButton oldbtn;
    private javax.swing.JButton paymentbtn;
    private javax.swing.JLabel phoneLab;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JButton savebtn;
    private javax.swing.JLabel searchLab;
    private javax.swing.JButton searchallbtn;
    private javax.swing.JButton searchallbtn1;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JPanel table;
    private javax.swing.JButton updatebtn;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
