/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controls.Tools;
import Entity.Accounts;
import Entity.Reports;
import Entity.Store;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmed
 */
public class ReportsFrm extends javax.swing.JFrame {

    /**
     * Creates new form ReportsFrm
     */
    public ReportsFrm() {
        initComponents();
        day.setVisible(false);
        day.setEnabled(false);
        days.setVisible(false);
        days.setEnabled(false);
        printbtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bar = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        closebtn = new javax.swing.JLabel();
        maxi = new javax.swing.JPanel();
        maxibtn = new javax.swing.JLabel();
        mini = new javax.swing.JPanel();
        minibtn = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        buttons = new javax.swing.JPanel();
        btnhome = new javax.swing.JButton();
        storedbtn = new javax.swing.JButton();
        accbtn = new javax.swing.JButton();
        billlinebtn = new javax.swing.JButton();
        billbtn = new javax.swing.JButton();
        search = new javax.swing.JPanel();
        printbtn = new javax.swing.JButton();
        panlSearch = new javax.swing.JPanel();
        daybtn = new javax.swing.JRadioButton();
        daysbtn = new javax.swing.JRadioButton();
        day = new javax.swing.JPanel();
        jDateOne = new com.toedter.calendar.JDateChooser();
        searchDaybtn = new javax.swing.JButton();
        days = new javax.swing.JPanel();
        searchDaysbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDateFrom = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jDateTo = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(26, 2, 2)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        bar.setPreferredSize(new java.awt.Dimension(100, 30));
        bar.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(26, 2, 2));
        jPanel10.setLayout(new java.awt.BorderLayout());

        close.setBackground(new java.awt.Color(36, 2, 2));
        close.setPreferredSize(new java.awt.Dimension(30, 30));
        close.setLayout(new java.awt.BorderLayout());

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_close_window_26px.png"))); // NOI18N
        closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closebtnMouseExited(evt);
            }
        });
        close.add(closebtn, java.awt.BorderLayout.CENTER);

        jPanel10.add(close, java.awt.BorderLayout.LINE_END);

        maxi.setBackground(new java.awt.Color(26, 2, 2));
        maxi.setPreferredSize(new java.awt.Dimension(30, 30));
        maxi.setLayout(new java.awt.BorderLayout());

        maxibtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_maximize_window_26px_1.png"))); // NOI18N
        maxibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maxibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxibtnMouseExited(evt);
            }
        });
        maxi.add(maxibtn, java.awt.BorderLayout.CENTER);

        jPanel10.add(maxi, java.awt.BorderLayout.CENTER);

        mini.setBackground(new java.awt.Color(26, 2, 2));
        mini.setPreferredSize(new java.awt.Dimension(30, 30));
        mini.setLayout(new java.awt.BorderLayout());

        minibtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_26px.png"))); // NOI18N
        minibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minibtnMouseExited(evt);
            }
        });
        mini.add(minibtn, java.awt.BorderLayout.CENTER);

        jPanel10.add(mini, java.awt.BorderLayout.LINE_START);

        bar.add(jPanel10, java.awt.BorderLayout.LINE_END);

        jPanel13.setBackground(new java.awt.Color(26, 2, 2));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(201, 201, 201));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("التقارير");
        jPanel13.add(jLabel6, java.awt.BorderLayout.CENTER);

        bar.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel14.setBackground(new java.awt.Color(26, 2, 2));
        jPanel14.setPreferredSize(new java.awt.Dimension(50, 100));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minlo.png"))); // NOI18N
        jPanel14.add(jLabel5, java.awt.BorderLayout.CENTER);

        bar.add(jPanel14, java.awt.BorderLayout.LINE_START);

        jPanel1.add(bar, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new java.awt.BorderLayout());

        buttons.setBackground(new java.awt.Color(255, 255, 255));
        buttons.setPreferredSize(new java.awt.Dimension(100, 200));
        buttons.setLayout(new java.awt.GridBagLayout());

        btnhome.setBackground(new java.awt.Color(26, 2, 2));
        btnhome.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnhome.setForeground(new java.awt.Color(201, 201, 201));
        btnhome.setText("الصفحة الرئيسية");
        btnhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 0);
        buttons.add(btnhome, gridBagConstraints);

        storedbtn.setBackground(new java.awt.Color(26, 2, 2));
        storedbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        storedbtn.setForeground(new java.awt.Color(201, 201, 201));
        storedbtn.setText("المخزن");
        storedbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        storedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storedbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 87;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 220, 80, 0);
        buttons.add(storedbtn, gridBagConstraints);

        accbtn.setBackground(new java.awt.Color(26, 2, 2));
        accbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        accbtn.setForeground(new java.awt.Color(201, 201, 201));
        accbtn.setText("إجمالي اليوم");
        accbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 90, 80, 0);
        buttons.add(accbtn, gridBagConstraints);

        billlinebtn.setBackground(new java.awt.Color(26, 2, 2));
        billlinebtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        billlinebtn.setForeground(new java.awt.Color(201, 201, 201));
        billlinebtn.setText("تفاصيل الفواتير");
        billlinebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        billlinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billlinebtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 80, 0);
        buttons.add(billlinebtn, gridBagConstraints);

        billbtn.setBackground(new java.awt.Color(26, 2, 2));
        billbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        billbtn.setForeground(new java.awt.Color(201, 201, 201));
        billbtn.setText("الفواتير");
        billbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        billbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 87;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 80, 27);
        buttons.add(billbtn, gridBagConstraints);

        body.add(buttons, java.awt.BorderLayout.PAGE_START);

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setPreferredSize(new java.awt.Dimension(100, 74));
        search.setLayout(new java.awt.GridBagLayout());

        printbtn.setBackground(new java.awt.Color(26, 2, 2));
        printbtn.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        printbtn.setForeground(new java.awt.Color(201, 201, 201));
        printbtn.setText("طباعة التقرير");
        printbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 40, 0, 0);
        search.add(printbtn, gridBagConstraints);

        panlSearch.setBackground(new java.awt.Color(255, 255, 255));
        panlSearch.setOpaque(false);
        panlSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daybtn.setBackground(new java.awt.Color(255, 255, 255));
        daybtn.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        daybtn.setForeground(new java.awt.Color(26, 2, 2));
        daybtn.setText("باليوم");
        daybtn.setOpaque(false);
        daybtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                daybtnItemStateChanged(evt);
            }
        });
        panlSearch.add(daybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        daysbtn.setBackground(new java.awt.Color(255, 255, 255));
        daysbtn.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        daysbtn.setForeground(new java.awt.Color(26, 2, 2));
        daysbtn.setText("بالفترة");
        daysbtn.setOpaque(false);
        daysbtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                daysbtnItemStateChanged(evt);
            }
        });
        panlSearch.add(daysbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        day.setBackground(new java.awt.Color(255, 255, 255));
        day.setOpaque(false);
        day.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDateOne.setBackground(new java.awt.Color(201, 201, 201));
        jDateOne.setForeground(new java.awt.Color(26, 2, 2));
        jDateOne.setDateFormatString("yyyy-MM-dd");
        day.add(jDateOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 8, 250, 25));

        searchDaybtn.setBackground(new java.awt.Color(26, 2, 2));
        searchDaybtn.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        searchDaybtn.setForeground(new java.awt.Color(201, 201, 201));
        searchDaybtn.setText("بحث");
        searchDaybtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchDaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDaybtnActionPerformed(evt);
            }
        });
        day.add(searchDaybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 70, 30));

        panlSearch.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 530, 40));

        days.setBackground(new java.awt.Color(255, 255, 255));
        days.setOpaque(false);
        days.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchDaysbtn.setBackground(new java.awt.Color(26, 2, 2));
        searchDaysbtn.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        searchDaysbtn.setForeground(new java.awt.Color(201, 201, 201));
        searchDaysbtn.setText("بحث");
        searchDaysbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchDaysbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDaysbtnActionPerformed(evt);
            }
        });
        days.add(searchDaysbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 70, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 2, 2));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("من");
        days.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 30, 25));

        jDateFrom.setBackground(new java.awt.Color(201, 201, 201));
        jDateFrom.setForeground(new java.awt.Color(26, 2, 2));
        jDateFrom.setDateFormatString("yyyy-MM-dd");
        days.add(jDateFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 8, 140, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 2, 2));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("إلى");
        days.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 10, 30, 25));

        jDateTo.setBackground(new java.awt.Color(201, 201, 201));
        jDateTo.setForeground(new java.awt.Color(26, 2, 2));
        jDateTo.setDateFormatString("yyyy-MM-dd");
        days.add(jDateTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 8, 140, 25));

        panlSearch.add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 530, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panlSearch.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 170, 5, 147);
        search.add(panlSearch, gridBagConstraints);

        body.add(search, java.awt.BorderLayout.CENTER);

        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setPreferredSize(new java.awt.Dimension(100, 370));
        table.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(184, 26, 61));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        table.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        body.add(table, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(body, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1281, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int btnR = 0;
    String btnD = "";

    public void clickButton(JButton button1,
            JButton button2, JButton button3, JButton button4, int numberbool) {
        if (numberbool == 1) {
            button1.setBackground(new Color(66, 2, 2));
            button1.setForeground(new Color(201, 201, 201));
            button2.setBackground(new Color(26, 2, 2));
            button2.setForeground(new Color(201, 201, 201));
            button3.setBackground(new Color(26, 2, 2));
            button3.setForeground(new Color(201, 201, 201));
            button4.setBackground(new Color(26, 2, 2));
            button4.setForeground(new Color(201, 201, 201));
        } else {
            button1.setBackground(new Color(26, 2, 2));
            button1.setForeground(new Color(201, 201, 201));
            button2.setBackground(new Color(66, 2, 2));
            button2.setForeground(new Color(201, 201, 201));
            button3.setBackground(new Color(66, 2, 2));
            button3.setForeground(new Color(201, 201, 201));
            button4.setBackground(new Color(66, 2, 2));
            button4.setForeground(new Color(201, 201, 201));
        }
    }

    Accounts ac = new Accounts();
    Store so = new Store();
    Reports rp = new Reports();

    HashMap pram = new HashMap();
    private void billbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billbtnActionPerformed
        btnR = 1;
        clickButton(billbtn, billlinebtn, accbtn, storedbtn, 1);

        panlSearch.setVisible(true);
        days.setVisible(false);
        day.setVisible(false);
        printbtn.setEnabled(false);
        jDateOne.setCalendar(null);
        jDateFrom.setCalendar(null);
        jDateTo.setCalendar(null);

        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("الربح بعد الخصم");
        table.addColumn("الربح قبل الخصم");
        table.addColumn("إجمالي بعد الخصم");
        table.addColumn("الخصومات");
        table.addColumn("إجمالي البيع");
        table.addColumn("إجمالي الشراء");
        table.addColumn("الموظف");
        table.addColumn("الوقت");
        table.addColumn("التاريخ");
        table.addColumn("الفاتورة");
        jTable1.setModel(table);
        Tools.tableUI(jTable1, 9);
    }//GEN-LAST:event_billbtnActionPerformed

    private void billlinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billlinebtnActionPerformed
        btnR = 2;
        clickButton(billlinebtn, billbtn, accbtn, storedbtn, 1);

        panlSearch.setVisible(true);
        days.setVisible(false);
        day.setVisible(false);
        printbtn.setEnabled(false);
        jDateOne.setCalendar(null);
        jDateFrom.setCalendar(null);
        jDateTo.setCalendar(null);

        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("الربح");
        table.addColumn("إجمالي البيع");
        table.addColumn("إجمالي الشراء");
        table.addColumn("سعر البيع");
        table.addColumn("سعر الشراء");
        table.addColumn("اللون");
        table.addColumn("العدد");
        table.addColumn("الموديل");
        table.addColumn("الفاتورة");
        table.addColumn("التاريخ");
        jTable1.setModel(table);
        Tools.tableUI(jTable1, 9);
    }//GEN-LAST:event_billlinebtnActionPerformed

    private void accbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accbtnActionPerformed
        btnR = 3;
        clickButton(accbtn, billlinebtn, billbtn, storedbtn, 1);

        panlSearch.setVisible(true);
        days.setVisible(false);
        day.setVisible(false);
        printbtn.setEnabled(false);
        jDateOne.setCalendar(null);
        jDateFrom.setCalendar(null);
        jDateTo.setCalendar(null);

        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("الربح بعد الخصم");
        table.addColumn("الربح قبل الخصم");
        table.addColumn("إجمالي بعد الخصم");
        table.addColumn("الخصومات");
        table.addColumn("المصروفات");
        table.addColumn("إجمالي البيع");
        table.addColumn("إجمالي الشراء");
        table.addColumn("التاريخ");
        jTable1.setModel(table);
        Tools.tableUI(jTable1, 7);
    }//GEN-LAST:event_accbtnActionPerformed

    private void storedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storedbtnActionPerformed
        btnR = 4;
        clickButton(storedbtn, billlinebtn, billbtn, accbtn, 1);

        panlSearch.setVisible(false);
        days.setVisible(false);
        day.setVisible(false);
        printbtn.setEnabled(true);

        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ملاحظات");
        table.addColumn("العدد");
        table.addColumn("المخزن");
        table.addColumn("سعر البيع");
        table.addColumn("سعر الشراء");
        table.addColumn("اللون");
        table.addColumn("الموديل");
        table.addColumn("القسم");
        table.addColumn("الباركود");
        table.addColumn("التسلسل");
        jTable1.setModel(table);
        Tools.tableUI(jTable1, 9);
        so.getAll(jTable1);
    }//GEN-LAST:event_storedbtnActionPerformed

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        if (btnR == 1) {
            System.out.println("R :" + btnR);
            if (btnD.equals("day") && jDateOne.getCalendar() != null) {

                String OneDate = dateFormat.format(jDateOne.getDate());
                pram.put("DateOnePram", OneDate);
                rp.setReport("billOneReport", pram);

            } else if (btnD.equals("days") && jDateFrom.getCalendar() != null && jDateTo.getCalendar() != null) {

                String DateFrom = dateFormat.format(jDateFrom.getDate());
                String DateTo = dateFormat.format(jDateTo.getDate());
                pram.put("DateFromPram", DateFrom);
                pram.put("DateToPram", DateTo);
                rp.setReport("billManyReport", pram);

            }
        } else if (btnR == 2) {
            if (btnD.equals("day") && jDateOne.getCalendar() != null) {

                String OneDate = dateFormat.format(jDateOne.getDate());
                pram.put("DateOnePram", OneDate);
                rp.setReport("billlineOneReport", pram);

            } else if (btnD.equals("days") && jDateFrom.getCalendar() != null && jDateTo.getCalendar() != null) {

                String DateFrom = dateFormat.format(jDateFrom.getDate());
                String DateTo = dateFormat.format(jDateTo.getDate());
                pram.put("DateFromPram", DateFrom);
                pram.put("DateToPram", DateTo);
                rp.setReport("billlineManyReport", pram);

            }

        } else if (btnR == 3) {
            if (btnD.equals("day") && jDateOne.getCalendar() != null) {

                String OneDate = dateFormat.format(jDateOne.getDate());
                pram.put("DateOnePram", OneDate);
                rp.setReport("accountsOneReport", pram);

            } else if (btnD.equals("days") && jDateFrom.getCalendar() != null && jDateTo.getCalendar() != null) {

                String DateFrom = dateFormat.format(jDateFrom.getDate());
                String DateTo = dateFormat.format(jDateTo.getDate());
                pram.put("DateFromPram", DateFrom);
                pram.put("DateToPram", DateTo);
                rp.setReport("accountsManyReport", pram);

            }
        } else if (btnR == 4) {

            rp.setReport("storedReport", null);
        }
    }//GEN-LAST:event_printbtnActionPerformed

    private void daybtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_daybtnItemStateChanged
        day.setVisible(true);
        day.setEnabled(true);
        days.setVisible(false);
        days.setEnabled(false);
        jDateOne.setCalendar(null);
        btnD = "day";
    }//GEN-LAST:event_daybtnItemStateChanged

    private void daysbtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_daysbtnItemStateChanged
        day.setVisible(false);
        day.setEnabled(false);
        days.setVisible(true);
        days.setEnabled(true);
        jDateFrom.setCalendar(null);
        jDateTo.setCalendar(null);
        btnD = "days";
    }//GEN-LAST:event_daysbtnItemStateChanged

    private void searchDaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDaybtnActionPerformed
        if (jDateOne.getCalendar() == null) {
            Tools.msgbox("ادخل التاريخ اولا !!");
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            java.sql.Date dateOne = java.sql.Date.valueOf(dateFormat.format(jDateOne.getDate()));

            if (btnR == 1) {
                ac.getAccByOneDate(dateOne, jTable1);
                printbtn.setEnabled(true);
            } else if (btnR == 2) {
                ac.getAllAccountsBillLineOne(dateOne, jTable1);
                printbtn.setEnabled(true);
            } else if (btnR == 3) {
                ac.getAllAccountsDayOne(dateOne, jTable1);
                printbtn.setEnabled(true);
            }

        }
    }//GEN-LAST:event_searchDaybtnActionPerformed

    private void searchDaysbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDaysbtnActionPerformed
        if (jDateFrom.getCalendar() == null || jDateTo.getCalendar() == null) {
            Tools.msgbox("ادخل التاريخ اولا !!");
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            java.sql.Date datef = java.sql.Date.valueOf(dateFormat.format(jDateFrom.getDate()));
            java.sql.Date datet = java.sql.Date.valueOf(dateFormat.format(jDateTo.getDate()));

            if (btnR == 1) {
                ac.getAccByManyDate(datef, datet, jTable1);
                printbtn.setEnabled(true);
            } else if (btnR == 2) {
                ac.getAllAccountsBillLineMany(datef, datet, jTable1);
                printbtn.setEnabled(true);
            } else if (btnR == 3) {
                ac.getAllAccountsDayMany(datef, datet, jTable1);
                printbtn.setEnabled(true);
            }
        }
    }//GEN-LAST:event_searchDaysbtnActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        this.dispose();
        Tools.openFram(new HomeFrm());
    }//GEN-LAST:event_btnhomeActionPerformed

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        int ifY = JOptionPane.showConfirmDialog(null, "هل تريد إغلاق البرنامج ؟");
        if (ifY == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_closebtnMouseClicked

    private void closebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseEntered
        close.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_closebtnMouseEntered

    private void closebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseExited
        close.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_closebtnMouseExited

    private void maxibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseClicked
        if (this.getExtendedState() != HomeFrm.MAXIMIZED_BOTH) {
            this.setExtendedState(HomeFrm.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(HomeFrm.NORMAL);
        }
    }//GEN-LAST:event_maxibtnMouseClicked

    private void maxibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseEntered
        maxi.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_maxibtnMouseEntered

    private void maxibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseExited
        maxi.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_maxibtnMouseExited

    private void minibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.setState(WIDTH);
        }
    }//GEN-LAST:event_minibtnMouseClicked

    private void minibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseEntered
        mini.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_minibtnMouseEntered

    private void minibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseExited
        mini.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_minibtnMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        buttonGroup1.add(daysbtn);
        buttonGroup1.add(daybtn);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accbtn;
    private javax.swing.JPanel bar;
    private javax.swing.JButton billbtn;
    private javax.swing.JButton billlinebtn;
    private javax.swing.JPanel body;
    private javax.swing.JButton btnhome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel buttons;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closebtn;
    private javax.swing.JPanel day;
    private javax.swing.JRadioButton daybtn;
    private javax.swing.JPanel days;
    private javax.swing.JRadioButton daysbtn;
    private com.toedter.calendar.JDateChooser jDateFrom;
    private com.toedter.calendar.JDateChooser jDateOne;
    private com.toedter.calendar.JDateChooser jDateTo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel maxi;
    private javax.swing.JLabel maxibtn;
    private javax.swing.JPanel mini;
    private javax.swing.JLabel minibtn;
    private javax.swing.JPanel panlSearch;
    private javax.swing.JButton printbtn;
    private javax.swing.JPanel search;
    private javax.swing.JButton searchDaybtn;
    private javax.swing.JButton searchDaysbtn;
    private javax.swing.JButton storedbtn;
    private javax.swing.JPanel table;
    // End of variables declaration//GEN-END:variables
}
