/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controls.Tools;
import DB.ConnectionDB;
import Entity.Reports;
import Entity.Storage;
import Entity.sale;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.util.HashMap;

/**
 *
 * @author ahmed
 */
public class SaleFrm extends javax.swing.JFrame {

    /**
     * Creates new form SallFrm
     */
    public SaleFrm() {
        initComponents();
        totalbuytxt.setVisible(false);
        hidepricebuytxt.setVisible(false);
        hidepricesaletxt.setVisible(false);
        priceAfter.setVisible(false);
        custNumtxt.setVisible(false);
        numid.setVisible(false);
        nameSale.setVisible(false);
        printBill.setEnabled(false);
        printLading.setEnabled(false);
        Tools.tableUI(jTsale, 5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        bar = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        closebtn = new javax.swing.JLabel();
        maxi = new javax.swing.JPanel();
        maxibtn = new javax.swing.JLabel();
        mini = new javax.swing.JPanel();
        minibtn = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        center = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        t = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        r = new javax.swing.JPanel();
        idbillLab = new javax.swing.JLabel();
        idBiltxt = new javax.swing.JTextField();
        timeLab = new javax.swing.JLabel();
        timetx = new javax.swing.JTextField();
        datejLab = new javax.swing.JLabel();
        Datetxt = new javax.swing.JTextField();
        l = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        costLab = new javax.swing.JLabel();
        costtxt = new javax.swing.JTextField();
        paiedLab = new javax.swing.JLabel();
        paiedtxt = new javax.swing.JTextField();
        discountLab = new javax.swing.JLabel();
        discounttxt = new javax.swing.JTextField();
        remainingLab = new javax.swing.JLabel();
        remainingtxt = new javax.swing.JTextField();
        totalLab = new javax.swing.JLabel();
        totaltxt = new javax.swing.JTextField();
        returnBbtn = new javax.swing.JButton();
        totalbuytxt = new javax.swing.JTextField();
        homebtn = new javax.swing.JButton();
        newbtn = new javax.swing.JButton();
        c = new javax.swing.JPanel();
        ri = new javax.swing.JPanel();
        sectionLab = new javax.swing.JLabel();
        jModel = new javax.swing.JComboBox<>();
        jsection = new javax.swing.JComboBox<>();
        modelLab = new javax.swing.JLabel();
        barcodetxt = new javax.swing.JTextField();
        barcodeLab = new javax.swing.JLabel();
        jdLineLab = new javax.swing.JLabel();
        idLinetxt = new javax.swing.JTextField();
        numid = new javax.swing.JTextField();
        hidepricebuytxt = new javax.swing.JTextField();
        hidepricesaletxt = new javax.swing.JTextField();
        priceAfter = new javax.swing.JTextField();
        ce = new javax.swing.JPanel();
        countLab = new javax.swing.JLabel();
        stockCountLab = new javax.swing.JLabel();
        stockCounttxt = new javax.swing.JTextField();
        colorLab = new javax.swing.JLabel();
        colortxt = new javax.swing.JTextField();
        priceLab = new javax.swing.JLabel();
        counttxt = new javax.swing.JTextField();
        pricetxt = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        le = new javax.swing.JPanel();
        nameLab = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        addressLab = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addresstxt = new javax.swing.JTextArea();
        phoneLab = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        custNumtxt = new javax.swing.JTextField();
        d = new javax.swing.JPanel();
        buttons = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        save = new javax.swing.JButton();
        printLading = new javax.swing.JButton();
        printBill = new javax.swing.JButton();
        table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTsale = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(26, 2, 2)));
        jPanel9.setLayout(new java.awt.BorderLayout());

        bar.setPreferredSize(new java.awt.Dimension(100, 30));
        bar.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(26, 2, 2));
        jPanel10.setLayout(new java.awt.BorderLayout());

        close.setBackground(new java.awt.Color(36, 2, 2));
        close.setPreferredSize(new java.awt.Dimension(30, 30));
        close.setLayout(new java.awt.BorderLayout());

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_close_window_26px.png"))); // NOI18N
        closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closebtnMouseExited(evt);
            }
        });
        close.add(closebtn, java.awt.BorderLayout.CENTER);

        jPanel10.add(close, java.awt.BorderLayout.LINE_END);

        maxi.setBackground(new java.awt.Color(26, 2, 2));
        maxi.setPreferredSize(new java.awt.Dimension(30, 30));
        maxi.setLayout(new java.awt.BorderLayout());

        maxibtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_maximize_window_26px_1.png"))); // NOI18N
        maxibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maxibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxibtnMouseExited(evt);
            }
        });
        maxi.add(maxibtn, java.awt.BorderLayout.CENTER);

        jPanel10.add(maxi, java.awt.BorderLayout.CENTER);

        mini.setBackground(new java.awt.Color(26, 2, 2));
        mini.setPreferredSize(new java.awt.Dimension(30, 30));
        mini.setLayout(new java.awt.BorderLayout());

        minibtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_26px.png"))); // NOI18N
        minibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minibtnMouseExited(evt);
            }
        });
        mini.add(minibtn, java.awt.BorderLayout.CENTER);

        jPanel10.add(mini, java.awt.BorderLayout.LINE_START);

        bar.add(jPanel10, java.awt.BorderLayout.LINE_END);

        jPanel13.setBackground(new java.awt.Color(26, 2, 2));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(201, 201, 201));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("البيع");
        jPanel13.add(jLabel2, java.awt.BorderLayout.CENTER);

        bar.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel14.setBackground(new java.awt.Color(26, 2, 2));
        jPanel14.setPreferredSize(new java.awt.Dimension(50, 100));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minlo.png"))); // NOI18N
        jPanel14.add(jLabel4, java.awt.BorderLayout.CENTER);

        bar.add(jPanel14, java.awt.BorderLayout.LINE_START);

        jPanel9.add(bar, java.awt.BorderLayout.PAGE_START);

        center.setBackground(new java.awt.Color(255, 255, 255));
        center.setPreferredSize(new java.awt.Dimension(100, 435));
        center.setLayout(new java.awt.BorderLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new java.awt.BorderLayout());

        t.setPreferredSize(new java.awt.Dimension(100, 150));
        t.setLayout(new java.awt.BorderLayout());

        top.setLayout(new java.awt.BorderLayout());

        r.setBackground(new java.awt.Color(255, 255, 255));
        r.setPreferredSize(new java.awt.Dimension(350, 100));
        r.setLayout(null);

        idbillLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        idbillLab.setForeground(new java.awt.Color(26, 2, 2));
        idbillLab.setText("رقم الفاتورة");
        r.add(idbillLab);
        idbillLab.setBounds(250, 20, 90, 30);

        idBiltxt.setEditable(false);
        idBiltxt.setBackground(new java.awt.Color(204, 204, 204));
        idBiltxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idBiltxt.setForeground(new java.awt.Color(26, 2, 2));
        idBiltxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        r.add(idBiltxt);
        idBiltxt.setBounds(80, 20, 130, 30);

        timeLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        timeLab.setForeground(new java.awt.Color(26, 2, 2));
        timeLab.setText("وقت الفاتورة");
        r.add(timeLab);
        timeLab.setBounds(250, 60, 65, 30);

        timetx.setEditable(false);
        timetx.setBackground(new java.awt.Color(204, 204, 204));
        timetx.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        timetx.setForeground(new java.awt.Color(26, 2, 2));
        timetx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        r.add(timetx);
        timetx.setBounds(80, 60, 130, 30);

        datejLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        datejLab.setForeground(new java.awt.Color(26, 2, 2));
        datejLab.setText("تاريخ الفاتورة");
        r.add(datejLab);
        datejLab.setBounds(250, 100, 90, 30);

        Datetxt.setEditable(false);
        Datetxt.setBackground(new java.awt.Color(204, 204, 204));
        Datetxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Datetxt.setForeground(new java.awt.Color(26, 2, 2));
        Datetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        r.add(Datetxt);
        Datetxt.setBounds(80, 100, 130, 30);

        top.add(r, java.awt.BorderLayout.LINE_END);

        l.setBackground(new java.awt.Color(255, 255, 255));
        l.setLayout(null);

        totalLabel.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(26, 2, 2));
        totalLabel.setText("الحساب النهائي");
        l.add(totalLabel);
        totalLabel.setBounds(820, 10, 76, 30);

        costLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        costLab.setForeground(new java.awt.Color(26, 2, 2));
        costLab.setText("المبلغ المطلوب");
        l.add(costLab);
        costLab.setBounds(810, 50, 80, 30);

        costtxt.setEditable(false);
        costtxt.setBackground(new java.awt.Color(201, 201, 201));
        costtxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        costtxt.setForeground(new java.awt.Color(26, 2, 2));
        costtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        costtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costtxtKeyTyped(evt);
            }
        });
        l.add(costtxt);
        costtxt.setBounds(810, 90, 80, 30);

        paiedLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        paiedLab.setForeground(new java.awt.Color(26, 2, 2));
        paiedLab.setText("المدفوع :");
        l.add(paiedLab);
        paiedLab.setBounds(700, 40, 49, 30);

        paiedtxt.setBackground(new java.awt.Color(201, 201, 201));
        paiedtxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        paiedtxt.setForeground(new java.awt.Color(26, 2, 2));
        paiedtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paiedtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paiedtxtActionPerformed(evt);
            }
        });
        l.add(paiedtxt);
        paiedtxt.setBounds(600, 40, 94, 30);

        discountLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        discountLab.setForeground(new java.awt.Color(26, 2, 2));
        discountLab.setText("الخصم :");
        l.add(discountLab);
        discountLab.setBounds(700, 80, 61, 30);

        discounttxt.setBackground(new java.awt.Color(201, 201, 201));
        discounttxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        discounttxt.setForeground(new java.awt.Color(26, 2, 2));
        discounttxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        discounttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discounttxtActionPerformed(evt);
            }
        });
        l.add(discounttxt);
        discounttxt.setBounds(600, 80, 94, 30);

        remainingLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        remainingLab.setForeground(new java.awt.Color(26, 2, 2));
        remainingLab.setText("الباقي :");
        l.add(remainingLab);
        remainingLab.setBounds(520, 40, 69, 30);

        remainingtxt.setEditable(false);
        remainingtxt.setBackground(new java.awt.Color(201, 201, 201));
        remainingtxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remainingtxt.setForeground(new java.awt.Color(26, 2, 2));
        remainingtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        l.add(remainingtxt);
        remainingtxt.setBounds(430, 40, 76, 30);

        totalLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        totalLab.setForeground(new java.awt.Color(26, 2, 2));
        totalLab.setText("الاجمالي :");
        l.add(totalLab);
        totalLab.setBounds(520, 80, 48, 30);

        totaltxt.setEditable(false);
        totaltxt.setBackground(new java.awt.Color(201, 201, 201));
        totaltxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totaltxt.setForeground(new java.awt.Color(26, 2, 2));
        totaltxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        l.add(totaltxt);
        totaltxt.setBounds(430, 80, 76, 30);

        returnBbtn.setBackground(new java.awt.Color(26, 2, 2));
        returnBbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        returnBbtn.setForeground(new java.awt.Color(201, 201, 201));
        returnBbtn.setText("رد الباقي");
        returnBbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBbtnActionPerformed(evt);
            }
        });
        l.add(returnBbtn);
        returnBbtn.setBounds(330, 40, 90, 30);

        totalbuytxt.setEditable(false);
        totalbuytxt.setBorder(null);
        l.add(totalbuytxt);
        totalbuytxt.setBounds(570, 20, 20, 16);

        homebtn.setBackground(new java.awt.Color(26, 2, 2));
        homebtn.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        homebtn.setForeground(new java.awt.Color(201, 201, 201));
        homebtn.setText("الصفحة الرئيسية");
        homebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        l.add(homebtn);
        homebtn.setBounds(30, 10, 200, 40);
        l.add(nameSale);
        nameSale.setBounds(40, 120, 0, 0);

        newbtn.setBackground(new java.awt.Color(26, 2, 2));
        newbtn.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        newbtn.setForeground(new java.awt.Color(201, 201, 201));
        newbtn.setText("فاتورة جديدة");
        newbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbtnActionPerformed(evt);
            }
        });
        l.add(newbtn);
        newbtn.setBounds(30, 90, 200, 40);

        top.add(l, java.awt.BorderLayout.CENTER);

        t.add(top, java.awt.BorderLayout.CENTER);

        body.add(t, java.awt.BorderLayout.PAGE_START);

        c.setBackground(new java.awt.Color(255, 255, 255));
        c.setLayout(new java.awt.BorderLayout());

        ri.setBackground(new java.awt.Color(255, 255, 255));
        ri.setPreferredSize(new java.awt.Dimension(400, 100));
        ri.setLayout(null);

        sectionLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        sectionLab.setForeground(new java.awt.Color(26, 2, 2));
        sectionLab.setText("اسم القسم :");
        ri.add(sectionLab);
        sectionLab.setBounds(280, 120, 110, 35);

        jModel.setBackground(new java.awt.Color(201, 201, 201));
        jModel.setForeground(new java.awt.Color(26, 2, 2));
        jModel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jModelItemStateChanged(evt);
            }
        });
        ri.add(jModel);
        jModel.setBounds(30, 170, 230, 35);

        jsection.setBackground(new java.awt.Color(201, 201, 201));
        jsection.setForeground(new java.awt.Color(26, 2, 2));
        jsection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jsectionItemStateChanged(evt);
            }
        });
        ri.add(jsection);
        jsection.setBounds(30, 120, 230, 35);

        modelLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        modelLab.setForeground(new java.awt.Color(26, 2, 2));
        modelLab.setText("اسم الموديل :");
        ri.add(modelLab);
        modelLab.setBounds(280, 170, 110, 35);

        barcodetxt.setBackground(new java.awt.Color(201, 201, 201));
        barcodetxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        barcodetxt.setForeground(new java.awt.Color(26, 2, 2));
        barcodetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barcodetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                barcodetxtKeyTyped(evt);
            }
        });
        ri.add(barcodetxt);
        barcodetxt.setBounds(30, 70, 230, 35);

        barcodeLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        barcodeLab.setForeground(new java.awt.Color(26, 2, 2));
        barcodeLab.setText("رقم الباركود :");
        ri.add(barcodeLab);
        barcodeLab.setBounds(280, 70, 110, 35);

        jdLineLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jdLineLab.setForeground(new java.awt.Color(26, 2, 2));
        jdLineLab.setText("الرقم :");
        ri.add(jdLineLab);
        jdLineLab.setBounds(280, 20, 110, 35);

        idLinetxt.setEditable(false);
        idLinetxt.setBackground(new java.awt.Color(201, 201, 201));
        idLinetxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        idLinetxt.setForeground(new java.awt.Color(26, 2, 2));
        idLinetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ri.add(idLinetxt);
        idLinetxt.setBounds(30, 20, 230, 35);

        numid.setBorder(null);
        numid.setOpaque(false);
        ri.add(numid);
        numid.setBounds(10, 20, 20, 20);

        hidepricebuytxt.setEditable(false);
        hidepricebuytxt.setBorder(null);
        hidepricebuytxt.setOpaque(false);
        ri.add(hidepricebuytxt);
        hidepricebuytxt.setBounds(20, 20, 0, 16);

        hidepricesaletxt.setEditable(false);
        hidepricesaletxt.setBorder(null);
        hidepricesaletxt.setOpaque(false);
        ri.add(hidepricesaletxt);
        hidepricesaletxt.setBounds(20, 20, 10, 16);

        priceAfter.setEditable(false);
        priceAfter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        priceAfter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ri.add(priceAfter);
        priceAfter.setBounds(0, 20, 10, 30);

        c.add(ri, java.awt.BorderLayout.LINE_END);

        ce.setBackground(new java.awt.Color(255, 255, 255));
        ce.setLayout(null);

        countLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        countLab.setForeground(new java.awt.Color(26, 2, 2));
        countLab.setText("العدد المطلوب :");
        ce.add(countLab);
        countLab.setBounds(360, 70, 110, 35);

        stockCountLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        stockCountLab.setForeground(new java.awt.Color(26, 2, 2));
        stockCountLab.setText("العدد في المخزن :");
        ce.add(stockCountLab);
        stockCountLab.setBounds(360, 20, 110, 35);

        stockCounttxt.setEditable(false);
        stockCounttxt.setBackground(new java.awt.Color(201, 201, 201));
        stockCounttxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stockCounttxt.setForeground(new java.awt.Color(26, 2, 2));
        stockCounttxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ce.add(stockCounttxt);
        stockCounttxt.setBounds(250, 20, 100, 35);

        colorLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        colorLab.setForeground(new java.awt.Color(26, 2, 2));
        colorLab.setText("اللون :");
        ce.add(colorLab);
        colorLab.setBounds(360, 170, 110, 35);

        colortxt.setEditable(false);
        colortxt.setBackground(new java.awt.Color(201, 201, 201));
        colortxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        colortxt.setForeground(new java.awt.Color(26, 2, 2));
        colortxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ce.add(colortxt);
        colortxt.setBounds(250, 170, 100, 35);

        priceLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        priceLab.setForeground(new java.awt.Color(26, 2, 2));
        priceLab.setText("سعر البيع :");
        ce.add(priceLab);
        priceLab.setBounds(360, 120, 110, 35);

        counttxt.setBackground(new java.awt.Color(201, 201, 201));
        counttxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        counttxt.setForeground(new java.awt.Color(26, 2, 2));
        counttxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        counttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                counttxtActionPerformed(evt);
            }
        });
        counttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                counttxtKeyTyped(evt);
            }
        });
        ce.add(counttxt);
        counttxt.setBounds(250, 70, 100, 35);

        pricetxt.setEditable(false);
        pricetxt.setBackground(new java.awt.Color(201, 201, 201));
        pricetxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pricetxt.setForeground(new java.awt.Color(26, 2, 2));
        pricetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ce.add(pricetxt);
        pricetxt.setBounds(250, 120, 100, 35);

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ce.add(image);
        image.setBounds(10, 30, 220, 150);

        c.add(ce, java.awt.BorderLayout.CENTER);

        le.setBackground(new java.awt.Color(255, 255, 255));
        le.setPreferredSize(new java.awt.Dimension(400, 100));
        le.setLayout(null);

        nameLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        nameLab.setForeground(new java.awt.Color(26, 2, 2));
        nameLab.setText("إسم العميل :");
        le.add(nameLab);
        nameLab.setBounds(240, 60, 110, 35);

        phonetxt.setBackground(new java.awt.Color(201, 201, 201));
        phonetxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        phonetxt.setForeground(new java.awt.Color(26, 2, 2));
        phonetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phonetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonetxtKeyTyped(evt);
            }
        });
        le.add(phonetxt);
        phonetxt.setBounds(30, 10, 200, 35);

        addressLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        addressLab.setForeground(new java.awt.Color(26, 2, 2));
        addressLab.setText("عنوان العميل :");
        le.add(addressLab);
        addressLab.setBounds(240, 110, 110, 35);

        jScrollPane2.setBackground(new java.awt.Color(201, 201, 201));
        jScrollPane2.setForeground(new java.awt.Color(26, 2, 2));
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        addresstxt.setBackground(new java.awt.Color(201, 201, 201));
        addresstxt.setColumns(20);
        addresstxt.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addresstxt.setForeground(new java.awt.Color(26, 2, 2));
        addresstxt.setRows(5);
        jScrollPane2.setViewportView(addresstxt);

        le.add(jScrollPane2);
        jScrollPane2.setBounds(30, 110, 200, 100);

        phoneLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        phoneLab.setForeground(new java.awt.Color(26, 2, 2));
        phoneLab.setText("رقم تليفون العميل :");
        le.add(phoneLab);
        phoneLab.setBounds(240, 10, 110, 35);

        nametxt.setBackground(new java.awt.Color(201, 201, 201));
        nametxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nametxt.setForeground(new java.awt.Color(26, 2, 2));
        nametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        le.add(nametxt);
        nametxt.setBounds(30, 60, 200, 35);

        custNumtxt.setEditable(false);
        custNumtxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        custNumtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        le.add(custNumtxt);
        custNumtxt.setBounds(370, 10, 10, 30);

        c.add(le, java.awt.BorderLayout.LINE_START);

        body.add(c, java.awt.BorderLayout.CENTER);

        d.setBackground(new java.awt.Color(255, 255, 255));
        d.setPreferredSize(new java.awt.Dimension(100, 50));
        d.setLayout(new java.awt.BorderLayout());

        buttons.setBackground(new java.awt.Color(255, 255, 255));
        buttons.setLayout(null);

        add.setBackground(new java.awt.Color(26, 2, 2));
        add.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        add.setForeground(new java.awt.Color(201, 201, 201));
        add.setText("إضافه");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        buttons.add(add);
        add.setBounds(1070, 10, 180, 30);

        deletebtn.setBackground(new java.awt.Color(26, 2, 2));
        deletebtn.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(201, 201, 201));
        deletebtn.setText("حذف صنف");
        deletebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        buttons.add(deletebtn);
        deletebtn.setBounds(860, 10, 180, 30);

        save.setBackground(new java.awt.Color(26, 2, 2));
        save.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        save.setForeground(new java.awt.Color(201, 201, 201));
        save.setText("حفظ ");
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        buttons.add(save);
        save.setBounds(30, 10, 200, 30);

        printLading.setBackground(new java.awt.Color(26, 2, 2));
        printLading.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        printLading.setForeground(new java.awt.Color(201, 201, 201));
        printLading.setText("طباعة بوليصة شحن");
        printLading.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printLading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printLadingActionPerformed(evt);
            }
        });
        buttons.add(printLading);
        printLading.setBounds(270, 10, 150, 30);

        printBill.setBackground(new java.awt.Color(26, 2, 2));
        printBill.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        printBill.setForeground(new java.awt.Color(201, 201, 201));
        printBill.setText("طباعة فاتورة");
        printBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBillActionPerformed(evt);
            }
        });
        buttons.add(printBill);
        printBill.setBounds(430, 10, 150, 30);

        d.add(buttons, java.awt.BorderLayout.CENTER);

        body.add(d, java.awt.BorderLayout.PAGE_END);

        center.add(body, java.awt.BorderLayout.CENTER);

        jPanel9.add(center, java.awt.BorderLayout.CENTER);

        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setPreferredSize(new java.awt.Dimension(100, 220));
        table.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane1.setOpaque(false);

        jTsale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "السعر", "العدد او الكمية", "القسم", "اسم الصنف", "رقم الفاتورة", "الرقم"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTsale.setFocusable(false);
        jTsale.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTsale.setRowHeight(12);
        jTsale.setSelectionBackground(new java.awt.Color(184, 26, 61));
        jTsale.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTsale.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTsale);

        table.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel9.add(table, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel9, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1281, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public byte[] profile = null;

    public void time() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss a");
                String texts_date = sdf.format(new Date());
                timetx.setText(texts_date);
            }

        }).start();

    }

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        this.dispose();
        Tools.openFram(new HomeFrm());
    }//GEN-LAST:event_homebtnActionPerformed

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        int ifY = JOptionPane.showConfirmDialog(null, "هل تريد إغلاق البرنامج ؟");
        if (ifY == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_closebtnMouseClicked

    private void closebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseEntered
        close.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_closebtnMouseEntered

    private void closebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseExited
        close.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_closebtnMouseExited

    private void maxibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseClicked
        if (this.getExtendedState() != HomeFrm.MAXIMIZED_BOTH) {
            this.setExtendedState(HomeFrm.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(HomeFrm.NORMAL);
        }
    }//GEN-LAST:event_maxibtnMouseClicked

    private void maxibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseEntered
        maxi.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_maxibtnMouseEntered

    private void maxibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseExited
        maxi.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_maxibtnMouseExited

    private void minibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.setState(WIDTH);
        }
    }//GEN-LAST:event_minibtnMouseClicked

    private void minibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseEntered
        mini.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_minibtnMouseEntered

    private void minibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseExited
        mini.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_minibtnMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        time();
        Date d = new Date();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");

        Datetxt.setText(f.format(d));
        image.setIcon(null);
        jsection.removeAllItems();
        DB.MethodsDB.fillCompo("sections", "section", jsection);
        DB.MethodsDB.fillCompo2("categories", "model", "section", jsection.getSelectedItem(), jModel);
        jsection.setSelectedItem(null);
        jModel.setSelectedItem(null);
        idBiltxt.setText(DB.MethodsDB.getAutoNumber("bill", "numberbill"));
        idLinetxt.setText(DB.MethodsDB.auto("billline", "number", "numberbill", idBiltxt.getText()));
        numid.setText(DB.MethodsDB.getAutoNumber("billline", "numberLine"));
        custNumtxt.setText(DB.MethodsDB.getAutoNumber("customer", "id"));


    }//GEN-LAST:event_formWindowOpened

    private void counttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_counttxtKeyTyped
        try {
            double prs = Double.parseDouble(pricetxt.getText());
            int cunt = Integer.parseInt(counttxt.getText());

            double t = prs * cunt;
            priceAfter.setText(String.valueOf(t));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_counttxtKeyTyped

    private void counttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counttxtActionPerformed
        try {
            double prs = Double.parseDouble(pricetxt.getText());
            int cunt = Integer.parseInt(counttxt.getText());

            double t = prs * cunt;
            priceAfter.setText(String.valueOf(t));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_counttxtActionPerformed
    sale se = new sale();
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if (!counttxt.getText().equals("") && Tools.ifNumber(counttxt.getText())) {
            try {
                double prs = Double.parseDouble(pricetxt.getText());
                int cunt = Integer.parseInt(counttxt.getText());

                double t = prs * cunt;
                priceAfter.setText(String.valueOf(t));

                if ("".equals(idBiltxt.getText()) || "".equals(numid.getText()) || "".equals(timetx.getText()) || "".equals(Datetxt.getText()) || "".equals(idLinetxt.getText()) || "".equals(jsection.getSelectedItem()) || "".equals(jModel.getSelectedItem()) || "".equals(counttxt.getText()) || "".equals(pricetxt.getText()) || "".equals(priceAfter.getText())) {
                    JOptionPane.showMessageDialog(this, "يجب ملئ البيانات اولا", "خطأ", JOptionPane.ERROR_MESSAGE);
                } else {

                    // الاستعلام عن عدد الصنف في المخزن وانقاص منه
                    try {
                        Connection c = ConnectionDB.setConn();
                        Statement stm = c.createStatement();
                        String sqls = "select count as count1 from categories where model ='" + jModel.getSelectedItem() + "'";
                        ResultSet rs = stm.executeQuery(sqls);
                        String num = "";
                        while (rs.next()) {
                            num = stm.getResultSet().getString("count1");
                        }

                        if (num == null || "".equals(num) || "0".equals(num)) {
                            JOptionPane.showMessageDialog(null, "لايوجد من هذا الصنف");
                        } else {
                            //  ادخال اصناف الفاتورة
                            String sqlsL = "INSERT INTO BILLLINE VALUES (" + numid.getText() + ", " + idBiltxt.getText() + ", '" + idLinetxt.getText() + "', '" + Datetxt.getText() + "' , '" + jsection.getSelectedItem() + "', '" + jModel.getSelectedItem() + "', '" + colortxt.getText() + "', '" + hidepricebuytxt.getText() + "', " + hidepricesaletxt.getText() + ", '" + counttxt.getText() + "', '" + priceAfter.getText() + "', '" + barcodetxt.getText() + "')";
                            boolean ifSL = DB.MethodsDB.runNunQuery(sqlsL);
                            if (ifSL) {
                                JOptionPane.showMessageDialog(this, "تم اضافة الصنف", "نجح", JOptionPane.WARNING_MESSAGE);

                                save.setEnabled(true);

                                idLinetxt.setText(DB.MethodsDB.auto("billline", "number", "numberbill", idBiltxt.getText()));
                                numid.setText(DB.MethodsDB.getAutoNumber("billline", "numberLine"));
                                se.getBillLine(idBiltxt.getText(), jTsale);

                                int countTotal = Integer.parseInt(num) - Integer.parseInt(counttxt.getText());
                                String update = "UPDATE CATEGORIES SET COUNT = '" + countTotal + "' WHERE model = '" + jModel.getSelectedItem() + "'";
                                DB.MethodsDB.runNunQuery(update);
                                System.out.println("done");

                                barcodetxt.setText("");
                                counttxt.setText("");
                                stockCounttxt.setText("");
                                jsection.setSelectedItem(null);
                                jModel.setSelectedItem(null);
                                pricetxt.setText("");
                                priceAfter.setText("");
                                discounttxt.setText("0");
                                colortxt.setText("");
                                image.setIcon(null);
                            } else {
                                JOptionPane.showMessageDialog(this, "لم يتم اضافة الصنف", "خطأ", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                        // الاستعلام عن مجموع او اجمالي الفاتورة

                        Connection con2 = ConnectionDB.setConn();
                        Statement stm2 = con2.createStatement();
                        String sqls2 = "select sum(price) as pr , sum(price_buy * count) as prb from billline where numberbill=" + idBiltxt.getText();
                        ResultSet rs2 = stm2.executeQuery(sqls2);
                        String num2 = "";
                        String numBuy = "";
                        while (rs2.next()) {
                            num2 = rs2.getString("pr");
                            numBuy = rs2.getString("prb");
                        }
                        if (num2 == null || "".equals(num2)) {
                            costtxt.setText("0");
                            totaltxt.setText("0");
                            totalbuytxt.setText("0");
                        } else {
                            costtxt.setText(num2);
                            totaltxt.setText(num2);
                            totalbuytxt.setText(numBuy);
                        }

                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }

                }
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(this, "يجب ملئ البيانات اولا", "خطأ", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_addActionPerformed
    Storage s = new Storage();
    private void barcodetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcodetxtKeyTyped
        try {
            Connection con = ConnectionDB.setConn();
            Statement stm = con.createStatement();
            String sqls = "select * from categories where barcode ='" + barcodetxt.getText() + "'";
            ResultSet rs = stm.executeQuery(sqls);
            String section = "";
            String model = "";
            String priceBuy = "0";
            String priceSale = "0";
            String color = "";
            String count = "";
            String id = "";
            while (rs.next()) {
                id = rs.getString(1);
                section = rs.getString(2);
                model = rs.getString(3);
                priceBuy = rs.getString(4);
                priceSale = rs.getString(5);
                color = rs.getString(7);
                count = rs.getString(10);
            }
            jsection.setSelectedItem(section);
            jModel.setSelectedItem(model);
            pricetxt.setText(priceSale);
            hidepricesaletxt.setText(priceSale);
            hidepricebuytxt.setText(priceBuy);
            colortxt.setText(color);
            stockCounttxt.setText(count);

            s.getImg(image, id);

//            profile = s.getImage();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "لا يوجد منتج بهذا الباركود !!");
        }
    }//GEN-LAST:event_barcodetxtKeyTyped

    private void jModelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jModelItemStateChanged
        try {
            Connection con = ConnectionDB.setConn();
            Statement stm = con.createStatement();
            String sqls = "select * from categories where model ='" + jModel.getSelectedItem() + "'";
            ResultSet rs = stm.executeQuery(sqls);
            String section = "";
            String barcode = "";
            String priceBuy = "0";
            String priceSale = "0";
            String color = "";
            String count = "";
            String id = "";
            while (rs.next()) {
                id = rs.getString(1);
                section = rs.getString(2);
                barcode = rs.getString(6);
                priceBuy = rs.getString(4);
                priceSale = rs.getString(5);
                color = rs.getString(7);
                count = rs.getString(10);
            }
            jsection.setSelectedItem(section);
            barcodetxt.setText(barcode);
            pricetxt.setText(priceSale);
            hidepricesaletxt.setText(priceSale);
            hidepricebuytxt.setText(priceBuy);
            colortxt.setText(color);
            stockCounttxt.setText(count);

            if (jModel.getSelectedItem() != null) {
                s.getImg(image, id);
            }
//            profile = s.getImage();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jModelItemStateChanged

    private void jsectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jsectionItemStateChanged
        try {
            DB.MethodsDB.fillCompo2("categories", "model", "section", jsection.getSelectedItem(), jModel);
            jModel.setSelectedItem(null);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jsectionItemStateChanged

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        int d = JOptionPane.showConfirmDialog(this, "هل تريد حذف الصنف المحدد ؟");
        if (d == JOptionPane.YES_OPTION) {
            int row = jTsale.getSelectedRow();
            String n = jTsale.getValueAt(row, 4).toString();
            String numB = jTsale.getValueAt(row, 5).toString();
            String nuCu = jTsale.getValueAt(row, 1).toString();
            String ca = jTsale.getValueAt(row, 3).toString();
            String prc = jTsale.getValueAt(row, 0).toString();

            // استعلام عن عدد الصنف في المخزن واضافة الصنف المحذوف
            try {
                Connection c = ConnectionDB.setConn();
                Statement stm = c.createStatement();
                String sqls = "select count as count1 from categories where model ='" + ca + "'";
                ResultSet rs = stm.executeQuery(sqls);
                String nu = "";
                while (rs.next()) {
                    nu = stm.getResultSet().getString("count1");
                }
                c.close();

                if (nu == null || "".equals(nu)) {
                    JOptionPane.showMessageDialog(null, "لايوجد من هذا الصنف");
                } else {

                    // حذف الصنف وارجاعة المخزن
                    String strD = "DELETE FROM BILLLINE WHERE NUMBER =" + numB + " and NumberBill=" + n;
                    boolean ifD = DB.MethodsDB.runNunQuery(strD);
                    if (ifD) {
                        JOptionPane.showMessageDialog(null, "تم حذف الصنف المحدد", "نجح", JOptionPane.WARNING_MESSAGE);

                        int countTotal = Integer.parseInt(nu) + Integer.parseInt(nuCu);
                        String update = "UPDATE CATEGORIES SET COUNT = '" + countTotal + "' WHERE model = '" + ca + "'";
                        DB.MethodsDB.runNunQuery(update);
                        System.out.println("done");

                        /*int remoNum = Integer.parseInt(numB);
                        category1.remove(ca);
                        coun1.remove(nuCu);
                        price1.remove(prc);*/
                    } else {
                        JOptionPane.showMessageDialog(null, "لم يتم حذف الصنف", "خطأ", JOptionPane.WARNING_MESSAGE);
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

            idBiltxt.setText(DB.MethodsDB.getAutoNumber("bill", "numberbill"));
            idLinetxt.setText(DB.MethodsDB.auto("billline", "number", "numberbill", idBiltxt.getText()));
            numid.setText(DB.MethodsDB.getAutoNumber("billline", "numberLine"));
            se.getBillLine(idBiltxt.getText(), jTsale);
            deletebtn.setEnabled(false);

            // الاستعلام عن مجموع او اجمالي الفاتورة
            try {
                Connection con = ConnectionDB.setConn();
                Statement stm = con.createStatement();
                String sqls = "select sum(price) as pr from billline where numberbill=" + idBiltxt.getText();
                ResultSet rs = stm.executeQuery(sqls);
                String num = "";
                while (rs.next()) {
                    num = stm.getResultSet().getString("pr");
                }
                con.close();
                if (num == null || "".equals(num)) {
                    costtxt.setText("0");
                    totaltxt.setText("0");
                } else {
                    costtxt.setText(num);
                    totaltxt.setText(num);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            // الاستعلام عن عدد اصناف الفاتورة
            /*try {
                Connection con = ConnectionDB.setConn();
                Statement stm = con.createStatement();
                String sqls = "select count(number) as num from billline where numberbill=" + idBiltxt.getText();
                ResultSet rs = stm.executeQuery(sqls);
                String num = "";
                while (rs.next()) {
                    num = stm.getResultSet().getString("num");
                }
                con.close();
                if (num == null || "".equals(num)) {
                    countCat.setText("0");
                } else {
                    countCat.setText(num);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }*/

        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void phonetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonetxtKeyTyped
        try {
            Connection con = ConnectionDB.setConn();
            Statement stm = con.createStatement();
            String sqls = "select * from customer where phone ='" + phonetxt.getText() + "'";
            ResultSet rs = stm.executeQuery(sqls);
            String name = "";
            String address = "";
            while (rs.next()) {
                name = rs.getString(2);
                address = rs.getString(4);
            }
            nametxt.setText(name);
            addresstxt.setText(address);

        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_phonetxtKeyTyped

    private void costtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costtxtKeyTyped
        if ("".equals(discounttxt.getText())) {
            String t = costtxt.getText();
            totaltxt.setText(t);
        }
    }//GEN-LAST:event_costtxtKeyTyped

    private void paiedtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paiedtxtActionPerformed
        try {
            double cs = Double.parseDouble(totaltxt.getText());
            double pa = Double.parseDouble(paiedtxt.getText());
            double tot = pa - cs;
            remainingtxt.setText(String.valueOf(tot));
            double r = Double.parseDouble(remainingtxt.getText());
            if (r > 0.0) {
                returnBbtn.setEnabled(true);
            } else {
                returnBbtn.setEnabled(false);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_paiedtxtActionPerformed

    private void discounttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discounttxtActionPerformed
        try {
            double cs = Double.parseDouble(costtxt.getText());
            double di = Double.parseDouble(discounttxt.getText());
            double tot = cs - di;
            totaltxt.setText(String.valueOf(tot));
        } catch (Exception e) {

        }
    }//GEN-LAST:event_discounttxtActionPerformed

    private void returnBbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBbtnActionPerformed
        String t = totaltxt.getText();
        paiedtxt.setText(t);
        remainingtxt.setText("0");
    }//GEN-LAST:event_returnBbtnActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if ("".equals(idBiltxt.getText()) || "".equals(timetx.getText()) || "".equals(Datetxt.getText()) || "".equals(costtxt.getText()) || "".equals(totaltxt.getText()) || "0".equals(costtxt.getText()) || "0".equals(totaltxt.getText())) {
            JOptionPane.showMessageDialog(this, "يجب إضافة المنتج اولا", "خطأ", JOptionPane.ERROR_MESSAGE);
        } else {
            String sqlsL = "INSERT INTO BILL VALUES (" + idBiltxt.getText() + ", '" + timetx.getText() + "', '" + Datetxt.getText() + "', '" + totalbuytxt.getText() + "', '" + costtxt.getText() + "' , '" + discounttxt.getText() + "', '" + totaltxt.getText() + "', '" + phonetxt.getText() + "', '" + nametxt.getText() + "', '" + addresstxt.getText() + "', '" + nameSale.getText() + "')";
            boolean ifSL = DB.MethodsDB.runNunQuery(sqlsL);
            if (ifSL) {
                if (!nametxt.getText().equals("") || !phonetxt.getText().equals("") || !addresstxt.getText().equals("")) {
                    String sqlsC = "INSERT INTO customer VALUES (" + custNumtxt.getText() + ", '" + nametxt.getText() + "', '" + phonetxt.getText() + "', '" + addresstxt.getText() + "')";
                    boolean ifSC = DB.MethodsDB.runNunQuery(sqlsC);
                }
                JOptionPane.showMessageDialog(this, "تم حفظ الفاتورة", "نجح", JOptionPane.WARNING_MESSAGE);
                printBill.setEnabled(true);
                printLading.setEnabled(true);
                save.setEnabled(false);
                deletebtn.setEnabled(false);
                se.getBillLine(idBiltxt.getText(), jTsale);
            } else {
                JOptionPane.showMessageDialog(this, "لم يتم حفظ الفاتورة", "خطأ", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveActionPerformed
    Reports rp = new Reports();
    HashMap pram = new HashMap();
    private void printBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBillActionPerformed
        pram.put("idParam", idBiltxt.getText());
        rp.setReport("Bill", pram);
    }//GEN-LAST:event_printBillActionPerformed

    private void printLadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printLadingActionPerformed
        pram.put("idParam", idBiltxt.getText());
        rp.setReport("LadingBill", pram);
    }//GEN-LAST:event_printLadingActionPerformed

    private void newbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbtnActionPerformed
        idBiltxt.setText(DB.MethodsDB.getAutoNumber("bill", "numberbill"));
        idLinetxt.setText(DB.MethodsDB.auto("billline", "number", "numberbill", idBiltxt.getText()));
        numid.setText(DB.MethodsDB.getAutoNumber("billline", "numberLine"));
        custNumtxt.setText(DB.MethodsDB.getAutoNumber("customer", "id"));
        printBill.setEnabled(false);
        printLading.setEnabled(false);
        save.setEnabled(false);

        deletebtn.setEnabled(false);
        barcodetxt.setText("");
        counttxt.setText("");
        colortxt.setText("");
        jsection.setSelectedItem(null);
        jModel.setSelectedItem(null);
        pricetxt.setText("");
        costtxt.setText("");
        paiedtxt.setText("");
        discounttxt.setText("");
        remainingtxt.setText("");
        totaltxt.setText("");
        image.setIcon(null);
        phonetxt.setText("");
        nametxt.setText("");
        addresstxt.setText("");
    }//GEN-LAST:event_newbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Datetxt;
    private javax.swing.JButton add;
    private javax.swing.JLabel addressLab;
    private javax.swing.JTextArea addresstxt;
    private javax.swing.JPanel bar;
    private javax.swing.JLabel barcodeLab;
    private javax.swing.JTextField barcodetxt;
    private javax.swing.JPanel body;
    private javax.swing.JPanel buttons;
    private javax.swing.JPanel c;
    private javax.swing.JPanel ce;
    private javax.swing.JPanel center;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel colorLab;
    private javax.swing.JTextField colortxt;
    private javax.swing.JLabel costLab;
    private javax.swing.JTextField costtxt;
    private javax.swing.JLabel countLab;
    private javax.swing.JTextField counttxt;
    private javax.swing.JTextField custNumtxt;
    private javax.swing.JPanel d;
    private javax.swing.JLabel datejLab;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel discountLab;
    private javax.swing.JTextField discounttxt;
    private javax.swing.JTextField hidepricebuytxt;
    private javax.swing.JTextField hidepricesaletxt;
    private javax.swing.JButton homebtn;
    private javax.swing.JTextField idBiltxt;
    private javax.swing.JTextField idLinetxt;
    private javax.swing.JLabel idbillLab;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jModel;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTsale;
    private javax.swing.JLabel jdLineLab;
    private javax.swing.JComboBox<String> jsection;
    private javax.swing.JPanel l;
    private javax.swing.JPanel le;
    private javax.swing.JPanel maxi;
    private javax.swing.JLabel maxibtn;
    private javax.swing.JPanel mini;
    private javax.swing.JLabel minibtn;
    private javax.swing.JLabel modelLab;
    private javax.swing.JLabel nameLab;
    public static final javax.swing.JLabel nameSale = new javax.swing.JLabel();
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton newbtn;
    private javax.swing.JTextField numid;
    private javax.swing.JLabel paiedLab;
    private javax.swing.JTextField paiedtxt;
    private javax.swing.JLabel phoneLab;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JTextField priceAfter;
    private javax.swing.JLabel priceLab;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JButton printBill;
    private javax.swing.JButton printLading;
    private javax.swing.JPanel r;
    private javax.swing.JLabel remainingLab;
    private javax.swing.JTextField remainingtxt;
    private javax.swing.JButton returnBbtn;
    private javax.swing.JPanel ri;
    private javax.swing.JButton save;
    private javax.swing.JLabel sectionLab;
    private javax.swing.JLabel stockCountLab;
    private javax.swing.JTextField stockCounttxt;
    private javax.swing.JPanel t;
    private javax.swing.JPanel table;
    private javax.swing.JLabel timeLab;
    private javax.swing.JTextField timetx;
    private javax.swing.JPanel top;
    private javax.swing.JLabel totalLab;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalbuytxt;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables
}
