/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controls.Tools;
import DB.MethodsDB;
import Entity.Storage;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ahmed
 */
public class StorageFrm extends javax.swing.JFrame {

    /**
     * Creates new form StorageFrm
     */
    public StorageFrm() {
        initComponents();
        Tools.tableUI(jTable1, 9);
        updatebtn.setEnabled(false);
        deletebtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel2 = new javax.swing.JPanel();
        bar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        closebtn = new javax.swing.JLabel();
        maxi = new javax.swing.JPanel();
        maxibtn = new javax.swing.JLabel();
        mini = new javax.swing.JPanel();
        minibtn = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        fildes = new javax.swing.JPanel();
        l = new javax.swing.JPanel();
        barcodeLab = new javax.swing.JLabel();
        barcodetxt = new javax.swing.JTextField();
        colorlab = new javax.swing.JLabel();
        colortxt = new javax.swing.JTextField();
        notesLab = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        c = new javax.swing.JPanel();
        secLab = new javax.swing.JLabel();
        addSectionbtn = new javax.swing.JButton();
        modelLab = new javax.swing.JLabel();
        addModelbtn = new javax.swing.JButton();
        imageLab = new javax.swing.JLabel();
        addImagebtn = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        r = new javax.swing.JPanel();
        idtxt = new javax.swing.JTextField();
        idLab = new javax.swing.JLabel();
        pbillLab = new javax.swing.JLabel();
        priceBilltxt = new javax.swing.JTextField();
        psaleLab = new javax.swing.JLabel();
        priceSaletxt = new javax.swing.JTextField();
        storenumLab = new javax.swing.JLabel();
        countLab = new javax.swing.JLabel();
        counttxt = new javax.swing.JTextField();
        addModelbtn1 = new javax.swing.JButton();
        search = new javax.swing.JPanel();
        searchLab = new javax.swing.JLabel();
        Searchtxt = new javax.swing.JTextField();
        table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btns = new javax.swing.JPanel();
        homebtn = new javax.swing.JButton();
        newCatbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(26, 2, 2)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        bar.setBackground(new java.awt.Color(26, 2, 2));
        bar.setPreferredSize(new java.awt.Dimension(100, 30));
        bar.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(26, 2, 2));
        jPanel3.setLayout(new java.awt.BorderLayout());

        close.setBackground(new java.awt.Color(36, 2, 2));
        close.setPreferredSize(new java.awt.Dimension(30, 30));
        close.setLayout(new java.awt.BorderLayout());

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_close_window_26px.png"))); // NOI18N
        closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closebtnMouseExited(evt);
            }
        });
        close.add(closebtn, java.awt.BorderLayout.CENTER);

        jPanel3.add(close, java.awt.BorderLayout.LINE_END);

        maxi.setBackground(new java.awt.Color(26, 2, 2));
        maxi.setPreferredSize(new java.awt.Dimension(30, 30));
        maxi.setLayout(new java.awt.BorderLayout());

        maxibtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_maximize_window_26px_1.png"))); // NOI18N
        maxibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maxibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxibtnMouseExited(evt);
            }
        });
        maxi.add(maxibtn, java.awt.BorderLayout.CENTER);

        jPanel3.add(maxi, java.awt.BorderLayout.CENTER);

        mini.setBackground(new java.awt.Color(26, 2, 2));
        mini.setPreferredSize(new java.awt.Dimension(30, 30));
        mini.setLayout(new java.awt.BorderLayout());

        minibtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_26px.png"))); // NOI18N
        minibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minibtnMouseExited(evt);
            }
        });
        mini.add(minibtn, java.awt.BorderLayout.CENTER);

        jPanel3.add(mini, java.awt.BorderLayout.LINE_START);

        bar.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(26, 2, 2));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(201, 201, 201));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("صنف جديد");
        jPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

        bar.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(26, 2, 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 100));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minlo.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        bar.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.add(bar, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setPreferredSize(new java.awt.Dimension(1000, 100));
        body.setLayout(new java.awt.BorderLayout());

        fildes.setLayout(new java.awt.BorderLayout());

        l.setBackground(new java.awt.Color(255, 255, 255));
        l.setPreferredSize(new java.awt.Dimension(350, 100));
        l.setLayout(null);

        barcodeLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        barcodeLab.setForeground(new java.awt.Color(26, 2, 2));
        barcodeLab.setText("رقم البار كود :");
        l.add(barcodeLab);
        barcodeLab.setBounds(240, 30, 80, 30);

        barcodetxt.setBackground(new java.awt.Color(187, 187, 187));
        barcodetxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        barcodetxt.setForeground(new java.awt.Color(0, 0, 0));
        barcodetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barcodetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l.add(barcodetxt);
        barcodetxt.setBounds(50, 30, 180, 30);

        colorlab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        colorlab.setForeground(new java.awt.Color(26, 2, 2));
        colorlab.setText("اللون :");
        l.add(colorlab);
        colorlab.setBounds(240, 90, 80, 30);

        colortxt.setBackground(new java.awt.Color(187, 187, 187));
        colortxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        colortxt.setForeground(new java.awt.Color(0, 0, 0));
        colortxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colortxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l.add(colortxt);
        colortxt.setBounds(50, 90, 180, 30);

        notesLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        notesLab.setForeground(new java.awt.Color(26, 2, 2));
        notesLab.setText("ملاحظات :");
        l.add(notesLab);
        notesLab.setBounds(240, 170, 80, 35);

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setAutoscrolls(true);

        notes.setBackground(new java.awt.Color(187, 187, 187));
        notes.setColumns(20);
        notes.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        notes.setForeground(new java.awt.Color(0, 0, 0));
        notes.setRows(5);
        notes.setBorder(null);
        jScrollPane2.setViewportView(notes);

        l.add(jScrollPane2);
        jScrollPane2.setBounds(50, 170, 180, 110);

        fildes.add(l, java.awt.BorderLayout.LINE_START);

        c.setBackground(new java.awt.Color(255, 255, 255));
        c.setPreferredSize(new java.awt.Dimension(400, 100));
        c.setLayout(null);

        secLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        secLab.setForeground(new java.awt.Color(26, 2, 2));
        secLab.setText("اسم القسم :");
        c.add(secLab);
        secLab.setBounds(260, 30, 90, 30);

        jSection.setBackground(new java.awt.Color(187, 187, 187));
        jSection.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jSection.setForeground(new java.awt.Color(0, 0, 0));
        jSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        c.add(jSection);
        jSection.setBounds(90, 30, 160, 30);

        addSectionbtn.setBackground(new java.awt.Color(26, 2, 2));
        addSectionbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addSectionbtn.setForeground(new java.awt.Color(201, 201, 201));
        addSectionbtn.setText("+");
        addSectionbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addSectionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSectionbtnActionPerformed(evt);
            }
        });
        c.add(addSectionbtn);
        addSectionbtn.setBounds(30, 30, 50, 30);

        modelLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        modelLab.setForeground(new java.awt.Color(26, 2, 2));
        modelLab.setText("اسم المودبل :");
        c.add(modelLab);
        modelLab.setBounds(260, 90, 90, 30);

        jModel.setBackground(new java.awt.Color(187, 187, 187));
        jModel.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jModel.setForeground(new java.awt.Color(0, 0, 0));
        jModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, addImagebtn, org.jdesktop.beansbinding.ObjectProperty.create(), jModel, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        c.add(jModel);
        jModel.setBounds(90, 90, 160, 30);

        addModelbtn.setBackground(new java.awt.Color(26, 2, 2));
        addModelbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addModelbtn.setForeground(new java.awt.Color(201, 201, 201));
        addModelbtn.setText("+");
        addModelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addModelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModelbtnActionPerformed(evt);
            }
        });
        c.add(addModelbtn);
        addModelbtn.setBounds(30, 90, 50, 30);

        imageLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        imageLab.setForeground(new java.awt.Color(26, 2, 2));
        imageLab.setText("الصورة :");
        c.add(imageLab);
        imageLab.setBounds(260, 150, 70, 35);

        addImagebtn.setBackground(new java.awt.Color(26, 2, 2));
        addImagebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addImagebtn.setForeground(new java.awt.Color(201, 201, 201));
        addImagebtn.setText("+");
        addImagebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, barcodetxt, org.jdesktop.beansbinding.ObjectProperty.create(), addImagebtn, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        addImagebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImagebtnActionPerformed(evt);
            }
        });
        c.add(addImagebtn);
        addImagebtn.setBounds(260, 190, 50, 30);

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c.add(image);
        image.setBounds(30, 160, 220, 150);

        fildes.add(c, java.awt.BorderLayout.CENTER);

        r.setBackground(new java.awt.Color(255, 255, 255));
        r.setPreferredSize(new java.awt.Dimension(320, 100));
        r.setLayout(null);

        idtxt.setEditable(false);
        idtxt.setBackground(new java.awt.Color(187, 187, 187));
        idtxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        idtxt.setForeground(new java.awt.Color(0, 0, 0));
        idtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r.add(idtxt);
        idtxt.setBounds(50, 30, 160, 30);

        idLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        idLab.setForeground(new java.awt.Color(26, 2, 2));
        idLab.setText("رقم التسلسل :");
        r.add(idLab);
        idLab.setBounds(220, 30, 90, 30);

        pbillLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        pbillLab.setForeground(new java.awt.Color(26, 2, 2));
        pbillLab.setText("سعر الشراء :");
        r.add(pbillLab);
        pbillLab.setBounds(220, 90, 90, 30);

        priceBilltxt.setBackground(new java.awt.Color(187, 187, 187));
        priceBilltxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        priceBilltxt.setForeground(new java.awt.Color(0, 0, 0));
        priceBilltxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        priceBilltxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r.add(priceBilltxt);
        priceBilltxt.setBounds(50, 90, 160, 30);

        psaleLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        psaleLab.setForeground(new java.awt.Color(26, 2, 2));
        psaleLab.setText("سعر البيع :");
        r.add(psaleLab);
        psaleLab.setBounds(220, 150, 90, 30);

        priceSaletxt.setBackground(new java.awt.Color(187, 187, 187));
        priceSaletxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        priceSaletxt.setForeground(new java.awt.Color(0, 0, 0));
        priceSaletxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        priceSaletxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r.add(priceSaletxt);
        priceSaletxt.setBounds(50, 150, 160, 30);

        storenumLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        storenumLab.setForeground(new java.awt.Color(26, 2, 2));
        storenumLab.setText(" المخزن :");
        r.add(storenumLab);
        storenumLab.setBounds(220, 210, 90, 30);

        jstoreNum.setBackground(new java.awt.Color(187, 187, 187));
        jstoreNum.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jstoreNum.setForeground(new java.awt.Color(0, 0, 0));
        jstoreNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        r.add(jstoreNum);
        jstoreNum.setBounds(50, 210, 160, 30);

        countLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        countLab.setForeground(new java.awt.Color(26, 2, 2));
        countLab.setText("العدد :");
        r.add(countLab);
        countLab.setBounds(220, 280, 90, 30);

        counttxt.setBackground(new java.awt.Color(187, 187, 187));
        counttxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        counttxt.setForeground(new java.awt.Color(0, 0, 0));
        counttxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        counttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSection, org.jdesktop.beansbinding.ObjectProperty.create(), counttxt, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        r.add(counttxt);
        counttxt.setBounds(50, 280, 160, 30);

        addModelbtn1.setBackground(new java.awt.Color(26, 2, 2));
        addModelbtn1.setFont(new java.awt.Font("Tahoma", 1, 6)); // NOI18N
        addModelbtn1.setForeground(new java.awt.Color(201, 201, 201));
        addModelbtn1.setText("+");
        addModelbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addModelbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModelbtn1ActionPerformed(evt);
            }
        });
        r.add(addModelbtn1);
        addModelbtn1.setBounds(10, 210, 35, 30);

        fildes.add(r, java.awt.BorderLayout.LINE_END);

        body.add(fildes, java.awt.BorderLayout.CENTER);

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setPreferredSize(new java.awt.Dimension(100, 50));
        search.setLayout(new java.awt.GridBagLayout());

        searchLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        searchLab.setForeground(new java.awt.Color(26, 2, 2));
        searchLab.setText("بحث :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 117);
        search.add(searchLab, gridBagConstraints);

        Searchtxt.setBackground(new java.awt.Color(187, 187, 187));
        Searchtxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Searchtxt.setForeground(new java.awt.Color(0, 0, 0));
        Searchtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Searchtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SearchtxtKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 558;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 210, 10, 0);
        search.add(Searchtxt, gridBagConstraints);

        body.add(search, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(body, java.awt.BorderLayout.CENTER);

        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setPreferredSize(new java.awt.Dimension(100, 250));
        table.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ملاحظات", "المخزن", "العدد", "اللون", "سعر البيع", "سعر الشراء", "الموديل", "القسم", "الباركود", "التسلسل"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(184, 26, 61));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        table.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(table, java.awt.BorderLayout.PAGE_END);

        btns.setBackground(new java.awt.Color(201, 201, 201));
        btns.setPreferredSize(new java.awt.Dimension(250, 100));
        btns.setLayout(new java.awt.GridBagLayout());

        homebtn.setBackground(new java.awt.Color(26, 2, 2));
        homebtn.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        homebtn.setForeground(new java.awt.Color(201, 201, 201));
        homebtn.setText("الصفحة الرئيسية");
        homebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 0, 20);
        btns.add(homebtn, gridBagConstraints);

        newCatbtn.setBackground(new java.awt.Color(26, 2, 2));
        newCatbtn.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        newCatbtn.setForeground(new java.awt.Color(201, 201, 201));
        newCatbtn.setText("إضافة صنف جديد");
        newCatbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newCatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCatbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 81;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 10, 0, 20);
        btns.add(newCatbtn, gridBagConstraints);

        updatebtn.setBackground(new java.awt.Color(26, 2, 2));
        updatebtn.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(201, 201, 201));
        updatebtn.setText("تعديل");
        updatebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 42, 20);
        btns.add(updatebtn, gridBagConstraints);

        deletebtn.setBackground(new java.awt.Color(26, 2, 2));
        deletebtn.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(201, 201, 201));
        deletebtn.setText("حذف الصنف المحدد");
        deletebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 10, 0, 20);
        btns.add(deletebtn, gridBagConstraints);

        savebtn.setBackground(new java.awt.Color(26, 2, 2));
        savebtn.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        savebtn.setForeground(new java.awt.Color(201, 201, 201));
        savebtn.setText("حفظ الصنف");
        savebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 10, 0, 20);
        btns.add(savebtn, gridBagConstraints);

        jPanel2.add(btns, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1281, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    String imgpath;
    public byte[] profile = null;
    Storage s = new Storage();

    private boolean setValues() {
        try {
            s.setId(Integer.parseInt(idtxt.getText()));
            s.setSection(jSection.getSelectedItem().toString());
            s.setModel(jModel.getSelectedItem().toString());
            s.setBarcode(barcodetxt.getText());
            s.setPrice_buy(Double.parseDouble(priceBilltxt.getText()));
            s.setPrice_sale(Double.parseDouble(priceSaletxt.getText()));
            s.setStoredName(jstoreNum.getSelectedItem().toString());
            s.setColor(colortxt.getText());
            s.setCount(Integer.parseInt(counttxt.getText()));
            s.setImage(profile);
            s.setNotes(notes.getText());
            return true;
        } catch (Exception ex) {
            Tools.msgbox("يجب ادخال البيانات بشكل صحيح !!");
            return false;
        }
    }

    public void chingImage(JLabel button, String resoursimg) {
        ImageIcon icon = new ImageIcon(getClass().getResource(resoursimg));
        button.setIcon(icon);
    }

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        int ifY = JOptionPane.showConfirmDialog(null, "هل تريد إغلاق البرنامج ؟");
        if (ifY == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_closebtnMouseClicked

    private void closebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseEntered
        close.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_closebtnMouseEntered

    private void closebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseExited
        close.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_closebtnMouseExited

    private void maxibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseClicked
        if (this.getExtendedState() != HomeFrm.MAXIMIZED_BOTH) {
            this.setExtendedState(HomeFrm.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(HomeFrm.NORMAL);
        }
    }//GEN-LAST:event_maxibtnMouseClicked

    private void maxibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseEntered
        maxi.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_maxibtnMouseEntered

    private void maxibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseExited
        maxi.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_maxibtnMouseExited

    private void minibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.setState(WIDTH);
        }
    }//GEN-LAST:event_minibtnMouseClicked

    private void minibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseEntered
        mini.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_minibtnMouseEntered

    private void minibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseExited
        mini.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_minibtnMouseExited

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        this.dispose();
        Tools.openFram(new HomeFrm());
    }//GEN-LAST:event_homebtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed

        if (idtxt.getText().equals("") || priceBilltxt.getText().equals("") || priceSaletxt.getText().equals("") || barcodetxt.getText().equals("") || counttxt.getText().equals("") || jSection.getSelectedItem() == null || jModel.getSelectedItem() == null) {
            Tools.msgbox("يجب ادخال البيانات اولا !!");
        } else {
            if (setValues()) {
                s.add();
                Tools.clearText(this);
                jModel.setSelectedItem(null);
                jSection.setSelectedItem(null);
                jstoreNum.setSelectedItem(null);
                image.setIcon(null);
                profile = null;
                idtxt.setText(MethodsDB.getAutoNumber("categories", "number"));
                s.getAllRows(jTable1);
            }
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        idtxt.setText(MethodsDB.getAutoNumber("categories", "number"));
        idtxt.requestFocus();
        s.getAllRows(jTable1);
        DB.MethodsDB.fillCompo("sections", "section", jSection);
        DB.MethodsDB.fillCompo("category", "Model", jModel);
        DB.MethodsDB.fillCompo("STORED", "STORED", jstoreNum);
        jSection.setSelectedItem(null);
        jModel.setSelectedItem(null);
        jstoreNum.setSelectedItem(null);
    }//GEN-LAST:event_formWindowOpened

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        if (idtxt.getText().equals("") || priceBilltxt.getText().equals("") || priceSaletxt.getText().equals("") || barcodetxt.getText().equals("") || counttxt.getText().equals("") || jSection.getSelectedItem() == null || jModel.getSelectedItem() == null) {
            Tools.msgbox("يجب ادخال البيانات اولا !!");
        } else {
            setValues();
            s.update();
            Tools.clearText(this);
            jModel.setSelectedItem(null);
            jSection.setSelectedItem(null);
            jstoreNum.setSelectedItem(null);
            image.setIcon(null);
            profile = null;
            idtxt.setText(MethodsDB.getAutoNumber("categories", "number"));
            s.getAllRows(jTable1);
            updatebtn.setEnabled(false);
            deletebtn.setEnabled(false);
            savebtn.setEnabled(true);
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        boolean ifyes = Tools.confirmMsg("هل تريد حذف الموديل");
        if (ifyes == true) {
            s.delete(idtxt.getText());
            Tools.clearText(this);
            String id = MethodsDB.getAutoNumber("categories", "number");
            idtxt.setText(id);
            jModel.setSelectedItem(null);
            jSection.setSelectedItem(null);
            jstoreNum.setSelectedItem(null);
            image.setIcon(null);
            profile = null;
            s.getAllRows(jTable1);
            savebtn.setEnabled(true);
            updatebtn.setEnabled(false);
            deletebtn.setEnabled(false);
            idtxt.requestFocus();
        } else {
            System.out.println("no deleted");
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void newCatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCatbtnActionPerformed
        Tools.clearText(this);
        String id = MethodsDB.getAutoNumber("categories", "number");
        idtxt.setText(id);
        s.getAllRows(jTable1);
        savebtn.setEnabled(true);
        updatebtn.setEnabled(false);
        deletebtn.setEnabled(false);
        idtxt.requestFocus();
        jModel.setSelectedItem(null);
        jSection.setSelectedItem(null);
        jstoreNum.setSelectedItem(null);
        image.setIcon(null);
        profile = null;
    }//GEN-LAST:event_newCatbtnActionPerformed

    private void addImagebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImagebtnActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("IMAGE FILES", "jpg", "png");
        chooser.addChoosableFileFilter(filter);
        int result = chooser.showDialog(null, "اختار صورة");
        if (result == JFileChooser.APPROVE_OPTION) {

            File f = chooser.getSelectedFile();
            String path = f.getAbsolutePath();
            ImageIcon img = new ImageIcon(path);
            Image imag = img.getImage().getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_AREA_AVERAGING);
            ImageIcon myimg = new ImageIcon(imag);
            image.setIcon(myimg);
            imgpath = path;
            try {
                File image = new File(imgpath);
                InputStream is = new FileInputStream(image);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte[] buf = new byte[1024];
                for (int redNum; (redNum = is.read(buf)) != -1;) {
                    bos.write(buf, 0, redNum);
                }
                profile = bos.toByteArray();
            } catch (IOException ex) {
                Logger.getLogger(UsersFrm.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("no data");
        }
    }//GEN-LAST:event_addImagebtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            int Ro = jTable1.getSelectedRow();
            String not = jTable1.getValueAt(Ro, 0).toString();
            String count = jTable1.getValueAt(Ro, 1).toString();
            String stored = jTable1.getValueAt(Ro, 2).toString();
            String color = jTable1.getValueAt(Ro, 3).toString();
            String priceSale = jTable1.getValueAt(Ro, 4).toString();
            String priceBuy = jTable1.getValueAt(Ro, 5).toString();
            String model = jTable1.getValueAt(Ro, 6).toString();
            String sec = jTable1.getValueAt(Ro, 7).toString();
            String barcod = jTable1.getValueAt(Ro, 8).toString();
            String num = jTable1.getValueAt(Ro, 9).toString();

            idtxt.setText(num);
            barcodetxt.setText(barcod);
            jModel.setSelectedItem(model);
            jSection.setSelectedItem(sec);
            priceBilltxt.setText(priceBuy);
            priceSaletxt.setText(priceSale);
            colortxt.setText(color);
            counttxt.setText(count);
            notes.setText(not);
            jstoreNum.setSelectedItem(stored);

            s.getImg(image, num);
            profile = s.getImage();

            updatebtn.setEnabled(true);
            deletebtn.setEnabled(true);
            savebtn.setEnabled(false);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void addSectionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSectionbtnActionPerformed
        Tools.openFram(new Section_Name());
    }//GEN-LAST:event_addSectionbtnActionPerformed

    private void addModelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModelbtnActionPerformed
        Tools.openFram(new Category_Name());
    }//GEN-LAST:event_addModelbtnActionPerformed

    private void SearchtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchtxtKeyTyped
        try {
            s.getBySearch(Searchtxt.getText(), jTable1);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SearchtxtKeyTyped

    private void addModelbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModelbtn1ActionPerformed
        Tools.openFram(new Stored_Name());
    }//GEN-LAST:event_addModelbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StorageFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StorageFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StorageFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StorageFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StorageFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Searchtxt;
    private javax.swing.JButton addImagebtn;
    private javax.swing.JButton addModelbtn;
    private javax.swing.JButton addModelbtn1;
    private javax.swing.JButton addSectionbtn;
    private javax.swing.JPanel bar;
    private javax.swing.JLabel barcodeLab;
    private javax.swing.JTextField barcodetxt;
    private javax.swing.JPanel body;
    private javax.swing.JPanel btns;
    private javax.swing.JPanel c;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel colorlab;
    private javax.swing.JTextField colortxt;
    private javax.swing.JLabel countLab;
    private javax.swing.JTextField counttxt;
    private javax.swing.JButton deletebtn;
    private javax.swing.JPanel fildes;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel idLab;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel image;
    private javax.swing.JLabel imageLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static final javax.swing.JComboBox<String> jModel = new javax.swing.JComboBox<>();
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static final javax.swing.JComboBox<String> jSection = new javax.swing.JComboBox<>();
    private javax.swing.JTable jTable1;
    public static final javax.swing.JComboBox<String> jstoreNum = new javax.swing.JComboBox<>();
    private javax.swing.JPanel l;
    private javax.swing.JPanel maxi;
    private javax.swing.JLabel maxibtn;
    private javax.swing.JPanel mini;
    private javax.swing.JLabel minibtn;
    private javax.swing.JLabel modelLab;
    private javax.swing.JButton newCatbtn;
    private javax.swing.JTextArea notes;
    private javax.swing.JLabel notesLab;
    private javax.swing.JLabel pbillLab;
    private javax.swing.JTextField priceBilltxt;
    private javax.swing.JTextField priceSaletxt;
    private javax.swing.JLabel psaleLab;
    private javax.swing.JPanel r;
    private javax.swing.JButton savebtn;
    private javax.swing.JPanel search;
    private javax.swing.JLabel searchLab;
    private javax.swing.JLabel secLab;
    private javax.swing.JLabel storenumLab;
    private javax.swing.JPanel table;
    private javax.swing.JButton updatebtn;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
