/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controls.Tools;
import DB.MethodsDB;
import Entity.Users;
import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class UsersFrm extends javax.swing.JFrame {

    /**
     * Creates new form UsersFrm
     */
    public UsersFrm() {
        initComponents();
        Tools.tableUI(jTable5, 3);
        updatebtn.setEnabled(false);
        deletebtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bar = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        closebtn = new javax.swing.JLabel();
        maxi = new javax.swing.JPanel();
        maxibtn = new javax.swing.JLabel();
        mini = new javax.swing.JPanel();
        minibtn = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        buttons = new javax.swing.JPanel();
        homebtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        newbtn = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        idLab = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        nameLab = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        userLab = new javax.swing.JLabel();
        usernamtxt = new javax.swing.JTextField();
        passLab = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JTextField();
        table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(26, 2, 2)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        bar.setPreferredSize(new java.awt.Dimension(1280, 30));
        bar.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(26, 2, 2));
        jPanel10.setLayout(new java.awt.BorderLayout());

        close.setBackground(new java.awt.Color(36, 2, 2));
        close.setPreferredSize(new java.awt.Dimension(30, 30));
        close.setLayout(new java.awt.BorderLayout());

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_close_window_26px.png"))); // NOI18N
        closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closebtnMouseExited(evt);
            }
        });
        close.add(closebtn, java.awt.BorderLayout.CENTER);

        jPanel10.add(close, java.awt.BorderLayout.LINE_END);

        maxi.setBackground(new java.awt.Color(26, 2, 2));
        maxi.setPreferredSize(new java.awt.Dimension(30, 30));
        maxi.setLayout(new java.awt.BorderLayout());

        maxibtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_maximize_window_26px_1.png"))); // NOI18N
        maxibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maxibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxibtnMouseExited(evt);
            }
        });
        maxi.add(maxibtn, java.awt.BorderLayout.CENTER);

        jPanel10.add(maxi, java.awt.BorderLayout.CENTER);

        mini.setBackground(new java.awt.Color(26, 2, 2));
        mini.setPreferredSize(new java.awt.Dimension(30, 30));
        mini.setLayout(new java.awt.BorderLayout());

        minibtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_26px.png"))); // NOI18N
        minibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minibtnMouseExited(evt);
            }
        });
        mini.add(minibtn, java.awt.BorderLayout.CENTER);

        jPanel10.add(mini, java.awt.BorderLayout.LINE_START);

        bar.add(jPanel10, java.awt.BorderLayout.LINE_END);

        jPanel13.setBackground(new java.awt.Color(26, 2, 2));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(201, 201, 201));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("المستخدمين");
        jPanel13.add(jLabel2, java.awt.BorderLayout.CENTER);

        bar.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel14.setBackground(new java.awt.Color(26, 2, 2));
        jPanel14.setPreferredSize(new java.awt.Dimension(50, 100));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minlo.png"))); // NOI18N
        jPanel14.add(jLabel4, java.awt.BorderLayout.CENTER);

        bar.add(jPanel14, java.awt.BorderLayout.LINE_START);

        jPanel1.add(bar, java.awt.BorderLayout.PAGE_START);

        buttons.setBackground(new java.awt.Color(201, 201, 201));
        buttons.setPreferredSize(new java.awt.Dimension(250, 350));
        buttons.setLayout(null);

        homebtn.setBackground(new java.awt.Color(26, 2, 2));
        homebtn.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        homebtn.setForeground(new java.awt.Color(201, 201, 201));
        homebtn.setText("الصفحة الرئيسية");
        homebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        buttons.add(homebtn);
        homebtn.setBounds(28, 5, 180, 40);

        savebtn.setBackground(new java.awt.Color(26, 2, 2));
        savebtn.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        savebtn.setForeground(new java.awt.Color(201, 201, 201));
        savebtn.setText("حفظ");
        savebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        buttons.add(savebtn);
        savebtn.setBounds(30, 150, 180, 38);

        updatebtn.setBackground(new java.awt.Color(26, 2, 2));
        updatebtn.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(201, 201, 201));
        updatebtn.setText("تعديل");
        updatebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        buttons.add(updatebtn);
        updatebtn.setBounds(30, 210, 180, 40);

        deletebtn.setBackground(new java.awt.Color(26, 2, 2));
        deletebtn.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(201, 201, 201));
        deletebtn.setText("حذف");
        deletebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        buttons.add(deletebtn);
        deletebtn.setBounds(30, 270, 180, 40);

        newbtn.setBackground(new java.awt.Color(26, 2, 2));
        newbtn.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        newbtn.setForeground(new java.awt.Color(201, 201, 201));
        newbtn.setText("جديد");
        newbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbtnActionPerformed(evt);
            }
        });
        buttons.add(newbtn);
        newbtn.setBounds(30, 90, 180, 38);

        jPanel1.add(buttons, java.awt.BorderLayout.LINE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(null);

        idLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        idLab.setForeground(new java.awt.Color(26, 2, 2));
        idLab.setText("رقم التسلسل :");
        body.add(idLab);
        idLab.setBounds(830, 120, 180, 35);

        idtxt.setEditable(false);
        idtxt.setBackground(new java.awt.Color(187, 187, 187));
        idtxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        idtxt.setForeground(new java.awt.Color(0, 0, 0));
        idtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        body.add(idtxt);
        idtxt.setBounds(630, 120, 180, 35);

        nameLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        nameLab.setForeground(new java.awt.Color(26, 2, 2));
        nameLab.setText("الاسم :");
        body.add(nameLab);
        nameLab.setBounds(830, 200, 180, 35);

        nametxt.setBackground(new java.awt.Color(187, 187, 187));
        nametxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        nametxt.setForeground(new java.awt.Color(0, 0, 0));
        nametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        body.add(nametxt);
        nametxt.setBounds(630, 200, 180, 35);

        userLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        userLab.setForeground(new java.awt.Color(26, 2, 2));
        userLab.setText("إسم المستخدم :");
        body.add(userLab);
        userLab.setBounds(330, 120, 180, 35);

        usernamtxt.setBackground(new java.awt.Color(187, 187, 187));
        usernamtxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        usernamtxt.setForeground(new java.awt.Color(0, 0, 0));
        usernamtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernamtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        body.add(usernamtxt);
        usernamtxt.setBounds(140, 120, 180, 35);

        passLab.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        passLab.setForeground(new java.awt.Color(26, 2, 2));
        passLab.setText("كلمة المرور :");
        body.add(passLab);
        passLab.setBounds(330, 200, 180, 35);

        passwordtxt.setBackground(new java.awt.Color(187, 187, 187));
        passwordtxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        passwordtxt.setForeground(new java.awt.Color(0, 0, 0));
        passwordtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        body.add(passwordtxt);
        passwordtxt.setBounds(140, 200, 180, 35);

        jPanel1.add(body, java.awt.BorderLayout.CENTER);

        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setPreferredSize(new java.awt.Dimension(1280, 300));
        table.setLayout(new java.awt.BorderLayout());

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "كلمة المرور", "إسم المستخدم", "الاسم", "التسلسل"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.setFocusable(false);
        jTable5.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable5.setSelectionBackground(new java.awt.Color(184, 26, 61));
        jTable5.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable5.getTableHeader().setReorderingAllowed(false);
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable5);

        table.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(table, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1281, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Users u = new Users();

    private void setValues() {
        u.setId(Integer.parseInt(idtxt.getText()));
        u.setName(nametxt.getText());
        u.setUsername(usernamtxt.getText());
        u.setPassword(passwordtxt.getText());
    }
    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        int ifY = JOptionPane.showConfirmDialog(null, "هل تريد إغلاق البرنامج ؟");
        if (ifY == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_closebtnMouseClicked

    private void closebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseEntered
        close.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_closebtnMouseEntered

    private void closebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseExited
        close.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_closebtnMouseExited

    private void maxibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseClicked
        if (this.getExtendedState() != HomeFrm.MAXIMIZED_BOTH) {
            this.setExtendedState(HomeFrm.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(HomeFrm.NORMAL);
        }
    }//GEN-LAST:event_maxibtnMouseClicked

    private void maxibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseEntered
        maxi.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_maxibtnMouseEntered

    private void maxibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxibtnMouseExited
        maxi.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_maxibtnMouseExited

    private void minibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.setState(WIDTH);
        }
    }//GEN-LAST:event_minibtnMouseClicked

    private void minibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseEntered
        mini.setBackground(new Color(75, 50, 50));
    }//GEN-LAST:event_minibtnMouseEntered

    private void minibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseExited
        mini.setBackground(new Color(26, 2, 2));
    }//GEN-LAST:event_minibtnMouseExited

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        this.dispose();
        Tools.openFram(new HomeFrm());
    }//GEN-LAST:event_homebtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        if (idtxt.getText().equals("") || usernamtxt.getText().equals("") || passwordtxt.getText().equals("")) {
            Tools.msgbox("يجب ادخال البيانات اولا !!");
        } else {
            setValues();
            u.add();
            Tools.clearText(this);
            idtxt.setText(MethodsDB.getAutoNumber("users", "number"));
            u.getAllRows(jTable5);
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        if (idtxt.getText().equals("") || usernamtxt.getText().equals("") || passwordtxt.getText().equals("")) {
            Tools.msgbox("يجب اختيار اليوزر من الجدول اولا !!");
        } else {
            setValues();
            u.update();
            savebtn.setEnabled(true);
            updatebtn.setEnabled(false);
            deletebtn.setEnabled(false);
            nametxt.requestFocus();
            Tools.clearText(this);
            idtxt.setText(MethodsDB.getAutoNumber("users", "number"));
            u.getAllRows(jTable5);
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        boolean ifyes = Tools.confirmMsg("هل تريد حذف اليوزر");
        if (ifyes == true) {
            u.delete(idtxt.getText());
            Tools.clearText(this);
            String id = MethodsDB.getAutoNumber("users", "number");
            idtxt.setText(id);
            u.getAllRows(jTable5);
            savebtn.setEnabled(true);
            updatebtn.setEnabled(false);
            deletebtn.setEnabled(false);
            nametxt.requestFocus();
        } else {
            System.out.println("no deleted");
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        idtxt.setText(MethodsDB.getAutoNumber("users", "number"));
        u.getAllRows(jTable5);
    }//GEN-LAST:event_formWindowOpened

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        try {
            int row = jTable5.getSelectedRow();
            String pass = jTable5.getValueAt(row, 0).toString();
            String user = jTable5.getValueAt(row, 1).toString();
            String nam = jTable5.getValueAt(row, 2).toString();
            String eid = jTable5.getValueAt(row, 3).toString();

            nametxt.setText(nam);
            usernamtxt.setText(user);
            passwordtxt.setText(pass);
            idtxt.setText(eid);

            savebtn.setEnabled(false);
            updatebtn.setEnabled(true);
            deletebtn.setEnabled(true);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jTable5MouseClicked

    private void newbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbtnActionPerformed
        Tools.clearText(this);
        idtxt.setText(MethodsDB.getAutoNumber("users", "number"));
        u.getAllRows(jTable5);
        savebtn.setEnabled(true);
        updatebtn.setEnabled(false);
        deletebtn.setEnabled(false);
        nametxt.requestFocus();
    }//GEN-LAST:event_newbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar;
    private javax.swing.JPanel body;
    private javax.swing.JPanel buttons;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closebtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel idLab;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable5;
    private javax.swing.JPanel maxi;
    private javax.swing.JLabel maxibtn;
    private javax.swing.JPanel mini;
    private javax.swing.JLabel minibtn;
    private javax.swing.JLabel nameLab;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton newbtn;
    private javax.swing.JLabel passLab;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JButton savebtn;
    private javax.swing.JPanel table;
    private javax.swing.JButton updatebtn;
    private javax.swing.JLabel userLab;
    private javax.swing.JTextField usernamtxt;
    // End of variables declaration//GEN-END:variables
}
